### ISSUE TITLE
Crash with latest version of patchouli (patchouli-1.16-39-FABRIC)

### ISSUE THREAD

**Issue by Riushda** [Chainmail-Studios/Astromine#200]
The game doesn't start with the latest versions of astromine and patchouli, if I remove patchouli mod from my mods folder then everything works fine.
Here's the crash report : 
```
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 6/08/20 23:24

Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'astromine'!
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:33)
	at net.minecraft.class_310.<init>(class_310.java:425)
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
Caused by: java.lang.NoClassDefFoundError: vazkii/patchouli/client/book/page/abstr/PageSimpleProcessingRecipe
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:156)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:156)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.github.chainmailstudios.astromine.registry.client.AstrominePatchouliPages.initialize(AstrominePatchouliPages.java:39)
	at com.github.chainmailstudios.astromine.AstromineClient.onInitializeClient(AstromineClient.java:46)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient$$Lambda$3692/918393724.accept(Unknown Source)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
	... 11 more
Caused by: java.lang.ClassNotFoundException: vazkii.patchouli.client.book.page.abstr.PageSimpleProcessingRecipe
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:161)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 25 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:33)
	at net.minecraft.class_310.<init>(class_310.java:425)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

-- System Details --
Details:
	Minecraft Version: 1.16.1
	Minecraft Version ID: 1.16.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1104688848 bytes (1053 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 12
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		adorn: Adorn 1.10.0+1.16.1
		antiqueatlas: Antique Atlas 5.3.0-fabric
		astromine: Astromine 1.5.2
		autoconfig1u: Auto Config v1 Updated 3.2.0-unstable
		betternether: Better Nether 3.5.4
		blue_endless_jankson: jankson 1.2.0
		byg: BYG 1.0.11
		campanion: Campanion 1.1.13+build.35
		cardinal-components-base: Cardinal Components API (base) 2.4.2
		cardinal-components-block: Cardinal Components API (blocks) 2.4.2
		cardinal-components-chunk: Cardinal Components API (chunks) 2.4.2
		cardinal-components-entity: Cardinal Components API (entities) 2.4.2
		cardinal-components-item: Cardinal Components API (items) 2.4.2
		cardinal-components-level: Cardinal Components API (world saves) 2.4.2
		cardinal-components-util: Cardinal Components API (utilities) 2.4.2
		cardinal-components-world: Cardinal Components API (worlds) 2.4.2
		cinderscapes: Cinderscapes 1.0.7+build.43-1.16.1
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.0.4
		cloth-config2: Cloth Config v4 4.6.0
		cloth-durability-bar-api-v1: Cloth Durability Bar API v1 1.0.7
		cotton: Cotton 1.0.7
		cotton-cauldron: Cotton Cauldron 1.0.4
		cotton-commons: Cotton Commons 1.0.4
		cotton-config: Cotton Config 1.0.0-rc.7
		cotton-datapack: Cotton Datapack 1.0.7
		cotton-logging: Cotton Logging 1.0.0-rc.4
		cotton-player-events: Cotton Player Events 1.0.2
		dishes: Delicious Dishes 1.0.3
		durabilityviewer: Giselbaers Durability Viewer 1.16-fabric0.13.1-1.8.1
		dynamicsoundfilters: Dynamic Sound Filters 1.1.2+1.16.1
		extraalchemy: Extra Alchemy 1.2.1
		fabric: Fabric API 0.16.2+build.385-1.16.1
		fabric-api-base: Fabric API Base 0.1.3+12a8474c7c
		fabric-biomes-v1: Fabric Biomes (v1) 0.2.7+059ea86602
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea8902
		fabric-command-api-v1: Fabric Command API (v1) 1.0.8+5ce5339802
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+52d3083602
		fabric-containers-v0: Fabric Containers (v0) 0.1.8+045df74f02
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.9+059ea86602
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d02
		fabric-dimensions-v1: fabric-dimensions-v1 1.0.0+a71b305302
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.3.3+7066030f02
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5b02
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.0+fe81e12502
		fabric-item-api-v1: Fabric Item API (v1) 1.0.0+16acbe5b02
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.0+438f963602
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+f404f3be02
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+3fa9f7c502
		fabric-language-kotlin: Fabric Language Kotlin 1.3.72+build.1
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+e83e061c02
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.0+386eb69e02
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce9902
		fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d602
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7b02
		fabric-networking-v0: Fabric Networking (v0) 0.1.10+e00ecb5f02
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.5.6+a2d21ddd02
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.6.1+a2d21ddd02
		fabric-particles-v1: fabric-particles-v1 0.2.1+0a6f2a7002
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.3.8+7dba2d6c02
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.2.13+eae12eb802
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.3.4+34d6c87102
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.0.1+5a0f9a6002
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d02
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.8+b7084faa02
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+5341049002
		fabric-rendering-v1: Fabric Rendering (v1) 1.1.2+346247d702
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.2.6+f41e209802
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+97324d1102
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.2.7+a4c57d8e02
		fabric-textures-v0: Fabric Textures (v0) 1.0.4+eae12eb802
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.0+55e0cc5f02
		fabricloader: Fabric Loader 0.9.0+build.204
		fermion: Fermion 2.1.191
		fermion-modkeys: Fermion Modifier Keys 1.8.180-snapshot
		fiber: fiber 0.23.0-1
		gbfabrictools: GBfabrictools 1.2.2+1.16
		jankson: Jankson 3.0.0+j1.2.0
		kirin: Kirin UI 1.6.4-1.16-rc1-1.16-SNAPSHOT
		lambdynlights: LambDynamicLights 1.2.2+1.16.1
		leaf-decay: Leaf Decay 1.2.0-1.16.1
		libblockattributes_core: LibBlockAttributes (Core) 0.7.1-pre.4
		libblockattributes_fluids: LibBlockAttributes (Fluids) 0.7.1-pre.4
		libblockattributes_items: LibBlockAttributes (Items) 0.7.1-pre.4
		libcd: LibCapableData 2.4.1+1.16-pre2
		libgamerule: LibGamerule ${version}
		libgui: LibGui 2.0.1+1.16.1
		libstructure: Libstructure 1.3
		lithium: Lithium 0.5.1
		magna: Magna 1.3.2-1.16.1
		mambience: MAmbience 2.1.0-1.16
		minecraft: Minecraft 1.16.1
		modmenu: Mod Menu 1.14.5+build.30
		nomoreglowingpots: No More Glowing Pots 1.0.2
		okzoomer: Ok Zoomer 3.0.1-20w12a
		org_jetbrains_annotations: annotations 17.0.0
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.3.72
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.3.72
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.3.72
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.3.72
		org_jetbrains_kotlinx_kotlinx-coroutines-core: kotlinx-coroutines-core 1.3.7
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.3.7
		parchment: Parchment 1.0.2+1.15.2
		patchouli: Patchouli 1.16-36-FABRIC
		phosphor: Phosphor 0.6.0+build.7
		playerabilitylib: Pal 1.2.0
		presencefootsteps: Presence Footsteps r26+1.16-rc1
		reach-entity-attributes: Reach Entity Attribute 1.0.1
		reborncore: Reborn Core 4.3.4+build.64
		roughlyenoughitems: Roughly Enough Items 4.10.5
		roughlyenoughresources: Roughly Enough Resources 2.0.2
		shapes: Shapes 2.0.0+build.10
		sleepvote: SleepVote ${version}
		sodium: Sodium 0.1.0
		spinnery: Spinnery 3.1.14
		spruceui: SpruceUI 1.5.8
		static-content: Static Content 1.0.0-1.16.1
		staticdata: Static Data 1.1.2
		team_reborn_energy: Energy 0.1.0
		techreborn: Tech Reborn 3.4.5+build.88
		terraform: Terraform 2.1.7+build.31
		terrestria: Terrestria 2.0.4+build.50
		traverse: Traverse 2.2.14+build.28
		waila: Hwyla 1.9.22
		winged: Winged Mod 1.16-1.2
		wolveswitharmor: Wolves With Armor 1.5.1-1.16.1
		wrenchable: Wrenchable 1.0.0+1.16.1
	Patchouli open book context: n/a
	Launched Version: fabric-loader-0.9.0+build.204-1.16.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NO CONTEXT
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>
```

**Comment by Shnupbups** [comment]
The crash report clearly says you're using `Patchouli 1.16-36-FABRIC`, not `Patchouli 1.16-39-FABRIC`. `39` should work just fine.
