### ISSUE TITLE
Astromine MAKES LAGS

### ISSUE THREAD

**Issue by Miros77** [Chainmail-Studios/Astromine#205]
...

**Comment by magneticflux-** [comment]
Your problem is having Thallium installed. It's a fake FPS boosting mod that doesn't do anything beyond what Lithium, Phosphor, and Sodium do. See here for more info: https://gist.github.com/LambdAurora/1f6a4a99af374ce500f250c6b42e8754#gistcomment-3380975

**Comment by Miros77** [comment]
Removed Thallium 
![2020-08-14_12 39 16](https://user-images.githubusercontent.com/59547044/90236402-63f23880-de2b-11ea-9feb-888f644e8108.png)
![2020-08-14_12 38 57](https://user-images.githubusercontent.com/59547044/90236440-72d8eb00-de2b-11ea-8cb2-cad082e75090.png)

LOG
[lag.txt](https://github.com/Chainmail-Studios/Astromine/files/5073854/lag.txt)

**Comment by magneticflux-** [comment]
Now you're throttling Sodium to 70fps lmao I have to be getting meme'd

**Comment by Miros77** [comment]
![2020-08-14_12 51 31](https://user-images.githubusercontent.com/59547044/90237509-0c54cc80-de2d-11ea-9337-c3719585b73c.png)
![2020-08-14_12 51 23](https://user-images.githubusercontent.com/59547044/90237528-14147100-de2d-11ea-81ec-816c6d57037f.png)

**Comment by Miros77** [comment]
> Your problem is having Thallium installed. It's a fake FPS boosting mod that doesn't do anything beyond what Lithium, Phosphor, and Sodium do. See here for more info: https://gist.github.com/LambdAurora/1f6a4a99af374ce500f250c6b42e8754#gistcomment-3380975

I will delete Thallium

**Comment by shedaniel** [comment]
You have a pentium from 2011, I don't think you should be expecting much from it.

**Comment by Miros77** [comment]
> You have a pentium from 2011, I don't think you should be expecting much from it.

my old laptop didn't lag  CPU : AMD Athlon x2 Drual-Core ql-64 

and the new laptop is lag CPU : Intel(R) Pentium CPU B960 @ 2.20GHz

**Comment by Miros77** [comment]
I have a question AMD is more powerful?

**Comment by Miros77** [comment]
> У вас есть pentium от 2011 года, я не думаю, что вы должны ожидать от него многого.



> You have a pentium from 2011, I don't think you should be expecting much from it.

release date: 1 October 2011

**Comment by Miros77** [comment]
optimization will be??

**Comment by vini2003** [comment]
The Pentium is still better than that Athlon.

**Comment by vini2003** [comment]
I am not certain what might be causing lagspikes, but I have a few ideas.

**Comment by Miros77** [comment]
maybe it's the lithium?

**Comment by Miros77** [comment]
![mods](https://user-images.githubusercontent.com/59547044/90263605-8cdcf280-de58-11ea-8ea8-21067263ec5d.JPG)

**Comment by Miros77** [comment]
[12:36:49] [Worker-Main-23/FATAL]: Mixin apply failed lithium.mixins.json:tag.TagImplMixin -> net.minecraft.class_3494$1: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException @Shadow field field_23686 was not located in the target class net.minecraft.class_3494$1. Using refmap mixins.lithium.refmap.json
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Shadow field field_23686 was not located in the target class net.minecraft.class_3494$1. Using refmap mixins.lithium.refmap.json
	at Not Enough Crashes deobfuscated stack trace.(1.14.4+build.15) ~[?:?]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachFields(MixinPreProcessorStandard.java:610) ~[sponge-mixin-0.8+build.18.jar:0.8+build.18+unknown-b18.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:289) ~[sponge-mixin-0.8+build.18.jar:0.8+build.18+unknown-b18.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:264) ~[sponge-mixin-0.8+build.18.jar:0.8+build.18+unknown-b18.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1272) ~[sponge-mixin-0.8+build.18.jar:0.8+build.18+unknown-b18.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:287) ~[sponge-mixin-0.8+build.18.jar:0.8+build.18+unknown-b18.git-unknown]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345) ~[sponge-mixin-0.8+build.18.jar:0.8+build.18+unknown-b18.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:570) ~[sponge-mixin-0.8+build.18.jar:0.8+build.18+unknown-b18.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351) ~[sponge-mixin-0.8+build.18.jar:0.8+build.18+unknown-b18.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191) ~[sponge-mixin-0.8+build.18.jar:0.8+build.18+unknown-b18.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) ~[sponge-mixin-0.8+build.18.jar:0.8+build.18+unknown-b18.git-unknown]
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) ~[fabric-loader-0.8.9+build.203.jar:0.8+build.18+unknown-b18.git-unknown]
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157) ~[fabric-loader-0.8.9+build.203.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143) ~[fabric-loader-0.8.9+build.203.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251]
	at net.minecraft.class_3494$class_5145.<init>(class_3494.java:39) ~[intermediary-fabric-loader-0.8.9+build.203-1.16.1.jar:?]
	at net.minecraft.tag.Tag$Builder.method_27066(Tag:122) ~[?:?]
	at java.util.ArrayList.forEach(Unknown Source) ~[?:1.8.0_251]
	at net.minecraft.tag.Tag$Builder.method_26780(Tag:122) ~[?:?]
	at net.minecraft.tag.TagContainer.method_18243(TagContainer:118) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) [?:1.8.0_251]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source) [?:1.8.0_251]
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:1.8.0_251]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) [?:1.8.0_251]
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:1.8.0_251]
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:1.8.0_251]

**Comment by Miros77** [comment]
this is because of the World Experiment Settings
![2020-08-14_19 17 03](https://user-images.githubusercontent.com/59547044/90271039-dda61880-de63-11ea-8d20-4bb170ee1e54.png)

**Comment by Miros77** [comment]
you can make support for your worlds??

**Comment by Miros77** [comment]
if I use mods for new worlds it's lag

**Comment by shedaniel** [comment]
Experimental features have nothing to do with lag.

**Comment by MariaTheDinkus** [comment]
I'm closing this for a few reasons:

1) We haven't heard any other reports of lag issues caused by Astromine.
2) Your hardware is clearly quite out of date.
3) This isn't a place to speculate about what's causing your FPS issues, feel free to figure that out in your free time.
4) This is increasingly becoming less and less focused on Astromine, and more on your own FPS issues.

I won't lock this for now, although I *will* do that if things continue to get further off-topic from Astromine.
