### ISSUE TITLE
Minor resource leak

### ISSUE THREAD

**Issue by Chocohead** [Chainmail-Studios/Astromine#251]
When running with debug mode on any resources which are opened but not closed are logged:

<details>
  <summary>Big old stacktrace</summary>

```
[Finalizer/WARN]: Leaked resource: 'minecraft:models/item/handheld.json' loaded from pack: 'Default'
java.lang.Exception
	at net.minecraft.class_3294$class_3295.<init>(class_3294.java:110)
	at net.minecraft.class_3294.method_14476(class_3294.java:89)
	at net.minecraft.class_3294.method_14486(class_3294.java:63)
	at net.minecraft.class_3304.method_14486(class_3304.java:64)
	at com.github.chainmailstudios.astromine.registry.client.AstromineClientModels.lambda$static$0(AstromineClientModels.java:48)
	at net.minecraft.class_3528.method_15332(class_3528.java:16)
	at com.github.chainmailstudios.astromine.discoveries.registry.client.AstromineDiscoveriesClientModels$1.method_4753(AstromineDiscoveriesClientModels.java:75)
	at net.minecraft.class_1088.getBakedModel(class_1088.java:655)
	at net.minecraft.class_1088.method_15878(class_1088.java:622)
	at net.minecraft.class_1088.lambda$uploadTextures$12(class_1088.java:285)
	at java.util.HashMap$KeySet.forEach(Unknown Source)
	at net.minecraft.class_1088.method_18177(class_1088.java:280)
	at net.minecraft.class_1092.method_18179(class_1092.java:67)
	at net.minecraft.class_1092.method_18788(class_1092.java:19)
	at net.minecraft.class_4080.method_18790(class_4080.java:13)
	at java.util.concurrent.CompletableFuture.uniAccept(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source)
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source)
	at net.minecraft.class_4010.method_18353(class_4010.java:40)
	at net.minecraft.class_4014.method_18365(class_4014.java:71)
	at net.minecraft.class_1255.execute(class_1255.java:104)
	at net.minecraft.class_4014.method_18367(class_4014.java:70)
	at net.minecraft.class_4010.method_18354(class_4010.java:38)
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniAccept(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source)
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.util.concurrent.CompletableFuture.postFire(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source)
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source)
	at net.minecraft.class_1255.execute(class_1255.java:104)
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniApply(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source)
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.util.concurrent.CompletableFuture.postFire(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source)
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source)
	at net.minecraft.class_4010.method_18353(class_4010.java:40)
	at net.minecraft.class_4014.method_18365(class_4014.java:71)
	at net.minecraft.class_1255.execute(class_1255.java:104)
	at net.minecraft.class_4014.method_18367(class_4014.java:70)
	at net.minecraft.class_4010.method_18354(class_4010.java:38)
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniAccept(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source)
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.util.concurrent.CompletableFuture.postFire(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source)
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source)
	at net.minecraft.class_1255.execute(class_1255.java:104)
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniApply(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source)
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.util.concurrent.CompletableFuture.postFire(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source)
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source)
	at net.minecraft.class_4010.method_18353(class_4010.java:40)
	at net.minecraft.class_4014.method_18365(class_4014.java:71)
	at net.minecraft.class_1255.execute(class_1255.java:104)
	at net.minecraft.class_4014.method_18367(class_4014.java:70)
	at net.minecraft.class_4010.method_18354(class_4010.java:38)
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniAccept(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source)
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.util.concurrent.CompletableFuture.postFire(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source)
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source)
	at net.minecraft.class_1255.execute(class_1255.java:104)
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniApply(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source)
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.util.concurrent.CompletableFuture.postFire(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source)
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source)
	at net.minecraft.class_4010.method_18353(class_4010.java:40)
	at net.minecraft.class_4014.method_18365(class_4014.java:71)
	at net.minecraft.class_1255.execute(class_1255.java:104)
	at net.minecraft.class_4014.method_18367(class_4014.java:70)
	at net.minecraft.class_4010.method_18354(class_4010.java:38)
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniAccept(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source)
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.util.concurrent.CompletableFuture.postFire(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source)
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source)
	at net.minecraft.class_1255.execute(class_1255.java:104)
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniApply(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source)
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.util.concurrent.CompletableFuture.postFire(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source)
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source)
	at net.minecraft.class_4010.method_18353(class_4010.java:40)
	at net.minecraft.class_4014.method_18365(class_4014.java:71)
	at net.minecraft.class_1255.execute(class_1255.java:104)
	at net.minecraft.class_4014.method_18367(class_4014.java:70)
	at net.minecraft.class_4010.method_18354(class_4010.java:38)
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniAccept(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source)
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.util.concurrent.CompletableFuture.postFire(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source)
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source)
	at net.minecraft.class_1255.execute(class_1255.java:104)
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniApply(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source)
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.util.concurrent.CompletableFuture.postFire(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source)
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source)
	at net.minecraft.class_4010.method_18353(class_4010.java:40)
	at net.minecraft.class_4014.method_18365(class_4014.java:71)
	at net.minecraft.class_1255.execute(class_1255.java:104)
	at net.minecraft.class_4014.method_18367(class_4014.java:70)
	at net.minecraft.class_4010.method_18354(class_4010.java:38)
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniAccept(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source)
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.util.concurrent.CompletableFuture.postFire(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source)
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source)
	at net.minecraft.class_1255.execute(class_1255.java:104)
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniApply(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source)
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.util.concurrent.CompletableFuture.postFire(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source)
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source)
	at com.mojang.blaze3d.systems.RenderSystem.replayQueue(RenderSystem.java:116)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:103)
	at net.minecraft.class_1041.method_15998(class_1041.java:384)
	at net.minecraft.class_310.method_1523(class_310.java:1043)
	at net.minecraft.class_310.method_1514(class_310.java:656)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
```
</details>

**Comment by vini2003** [comment]
Solved.
