### ISSUE TITLE
Crash when opening machine gui

### ISSUE THREAD

**Issue by ghost** [Chainmail-Studios/Astromine#255]
How to reproduce:

- Astromine 1.9.2+fabric-1.16.2 downloaded from the CurseForge releases page
- Fabric API versions 0.19 and 0.20.1, JDK 8-14 doesn't really seem to matter
- Create a new world, place some Astromine machine and right-click it

<details>
  <summary>Crash log</summary>

```
  
[12:47:25] [main/FATAL]: Unreported exception thrown!
java.lang.NoSuchMethodError: kotlin.jvm.internal.MutablePropertyReference1Impl.<init>(Ljava/lang/Class;Ljava/lang/String;Ljava/lang/String;I)V
	at com.github.vini2003.blade.common.widget.base.AbstractWidget.<clinit>(AbstractWidget.java) ~[878aba0b-0473-43c6-8cab-81ed92c1a622.jar:?]
	at com.github.chainmailstudios.astromine.common.screenhandler.base.block.ComponentBlockEntityScreenHandler.initialize(ComponentBlockEntityScreenHandler.java:89) ~[2193b0fe-35d9-4f94-884e-09ec75ca5573.jar:?]
	at com.github.chainmailstudios.astromine.common.screenhandler.base.block.ComponentBlockEntityEnergyItemScreenHandler.initialize(ComponentBlockEntityEnergyItemScreenHandler.java:49) ~[2193b0fe-35d9-4f94-884e-09ec75ca5573.jar:?]
	at com.github.chainmailstudios.astromine.technologies.common.screenhandler.AlloySmelterScreenHandler.initialize(AlloySmelterScreenHandler.java:50) ~[5e5ff8e7-c248-4f5e-b3b1-b52388b129b5.jar:?]
	at com.github.vini2003.blade.client.handler.BaseHandledScreen.method_25426(BaseHandledScreen.java:28) ~[878aba0b-0473-43c6-8cab-81ed92c1a622.jar:?]
	at net.minecraft.class_437.method_25423(class_437.java:325) ~[intermediary-minecraft-1.16.2-client.jar:?]
	at net.minecraft.class_310.method_1507(class_310.java:897) ~[intermediary-minecraft-1.16.2-client.jar:?]
	at net.fabricmc.fabric.impl.screenhandler.client.ClientNetworking.openScreen(ClientNetworking.java:82) ~[7bd7187f-6304-4487-8e9a-20aef6678f3e.jar:?]
	at net.fabricmc.fabric.impl.screenhandler.client.ClientNetworking.lambda$null$0(ClientNetworking.java:51) ~[7bd7187f-6304-4487-8e9a-20aef6678f3e.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:144) ~[intermediary-minecraft-1.16.2-client.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[intermediary-minecraft-1.16.2-client.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:118) ~[intermediary-minecraft-1.16.2-client.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:103) ~[intermediary-minecraft-1.16.2-client.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:990) ~[intermediary-minecraft-1.16.2-client.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:656) [intermediary-minecraft-1.16.2-client.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:215) [intermediary-minecraft-1.16.2-client.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_265]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_265]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_265]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_265]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192) [fabric-loader-0.9.2+build.206.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140) [fabric-loader-0.9.2+build.206.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26) [fabric-loader-0.9.2+build.206.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_265]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_265]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_265]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_265]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
[12:47:27] [Server thread/INFO]: Stopping server
[12:47:27] [Server thread/INFO]: Saving players
[12:47:27] [Server thread/INFO]: PetaByteBoy lost connection: Disconnected
[12:47:27] [Server thread/INFO]: PetaByteBoy left the game
[12:47:27] [Server thread/INFO]: Stopping singleplayer server as player logged out
[12:47:27] [Server thread/INFO]: Saving worlds
[12:47:27] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:overworld
[12:47:28] [Server thread/INFO]: ThreadedAnvilChunkStorage (New World): All chunks are saved
[12:47:28] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_nether
[12:47:28] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[12:47:28] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_end
[12:47:28] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[12:47:28] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/astromine:mars
[12:47:28] [Server thread/INFO]: ThreadedAnvilChunkStorage (mars): All chunks are saved
[12:47:28] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/astromine:vulcan
[12:47:28] [Server thread/INFO]: ThreadedAnvilChunkStorage (vulcan): All chunks are saved
[12:47:28] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/astromine:earth_space
[12:47:28] [Server thread/INFO]: ThreadedAnvilChunkStorage (earth_space): All chunks are saved
[12:47:28] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/astromine:moon
[12:47:28] [Server thread/INFO]: ThreadedAnvilChunkStorage (moon): All chunks are saved
[12:47:28] [Server thread/INFO]: ThreadedAnvilChunkStorage (New World): All chunks are saved
[12:47:28] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[12:47:28] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[12:47:28] [Server thread/INFO]: ThreadedAnvilChunkStorage (mars): All chunks are saved
[12:47:28] [Server thread/INFO]: ThreadedAnvilChunkStorage (vulcan): All chunks are saved
[12:47:28] [Server thread/INFO]: ThreadedAnvilChunkStorage (earth_space): All chunks are saved
[12:47:28] [Server thread/INFO]: ThreadedAnvilChunkStorage (moon): All chunks are saved
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 9/6/20 12:47 PM
Description: Unexpected error

java.lang.NoSuchMethodError: kotlin.jvm.internal.MutablePropertyReference1Impl.<init>(Ljava/lang/Class;Ljava/lang/String;Ljava/lang/String;I)V
	at com.github.vini2003.blade.common.widget.base.AbstractWidget.<clinit>(AbstractWidget.java)
	at com.github.chainmailstudios.astromine.common.screenhandler.base.block.ComponentBlockEntityScreenHandler.initialize(ComponentBlockEntityScreenHandler.java:89)
	at com.github.chainmailstudios.astromine.common.screenhandler.base.block.ComponentBlockEntityEnergyItemScreenHandler.initialize(ComponentBlockEntityEnergyItemScreenHandler.java:49)
	at com.github.chainmailstudios.astromine.technologies.common.screenhandler.AlloySmelterScreenHandler.initialize(AlloySmelterScreenHandler.java:50)
	at com.github.vini2003.blade.client.handler.BaseHandledScreen.method_25426(BaseHandledScreen.java:28)
	at net.minecraft.class_437.method_25423(class_437.java:325)
	at net.minecraft.class_310.method_1507(class_310.java:897)
	at net.fabricmc.fabric.impl.screenhandler.client.ClientNetworking.openScreen(ClientNetworking.java:82)
	at net.fabricmc.fabric.impl.screenhandler.client.ClientNetworking.lambda$null$0(ClientNetworking.java:51)
	at net.minecraft.class_1255.method_18859(class_1255.java:144)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:118)
	at net.minecraft.class_1255.method_5383(class_1255.java:103)
	at net.minecraft.class_310.method_1523(class_310.java:990)
	at net.minecraft.class_310.method_1514(class_310.java:656)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.github.vini2003.blade.common.widget.base.AbstractWidget.<clinit>(AbstractWidget.java)
	at com.github.chainmailstudios.astromine.common.screenhandler.base.block.ComponentBlockEntityScreenHandler.initialize(ComponentBlockEntityScreenHandler.java:89)
	at com.github.chainmailstudios.astromine.common.screenhandler.base.block.ComponentBlockEntityEnergyItemScreenHandler.initialize(ComponentBlockEntityEnergyItemScreenHandler.java:49)
	at com.github.chainmailstudios.astromine.technologies.common.screenhandler.AlloySmelterScreenHandler.initialize(AlloySmelterScreenHandler.java:50)
	at com.github.vini2003.blade.client.handler.BaseHandledScreen.method_25426(BaseHandledScreen.java:28)
	at net.minecraft.class_437.method_25423(class_437.java:325)
	at net.minecraft.class_310.method_1507(class_310.java:897)
	at net.fabricmc.fabric.impl.screenhandler.client.ClientNetworking.openScreen(ClientNetworking.java:82)
	at net.fabricmc.fabric.impl.screenhandler.client.ClientNetworking.lambda$null$0(ClientNetworking.java:51)
	at net.minecraft.class_1255.method_18859(class_1255.java:144)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:118)

-- Affected level --
Details:
	All players: 1 total; [class_746['PetaByteBoy'/179, l='ClientLevel', x=-259.50, y=69.00, z=202.50]]
	Chunk stats: Client Chunk Cache: 841, 484
	Level dimension: minecraft:overworld
	Level spawn location: World: (-256,69,208), Chunk: (at 0,4,0 in -16,13; contains blocks -256,0,208 to -241,255,223), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 1132 game time, 1132 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:449)
	at net.minecraft.class_310.method_1587(class_310.java:2183)
	at net.minecraft.class_310.method_1514(class_310.java:679)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.16.2
	Minecraft Version ID: 1.16.2
	Operating System: Linux (amd64) version 5.9.0-rc2
	Java Version: 1.8.0_265, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2955164848 bytes (2818 MB) / 4451729408 bytes (4245 MB) up to 7635730432 bytes (7282 MB)
	CPUs: 8
	JVM Flags: 2 total; -Xms1024m -Xmx8192m
	Fabric Mods: 
		astromine: Astromine 1.9.2+fabric-1.16.2
		astromine-core: Astromine: Core 1.9.2+fabric-1.16.2
		astromine-discoveries: Astromine: Discoveries 1.9.2+fabric-1.16.2
		astromine-foundations: Astromine: Foundations 1.9.2+fabric-1.16.2
		astromine-technologies: Astromine: Technologies 1.9.2+fabric-1.16.2
		astromine-transportations: Astromine: Transportations 1.9.2+fabric-1.16.2
		autoconfig1u: Auto Config v1 Updated 3.2.2
		blade: Blade 1.0.1
		blue_endless_jankson: jankson 1.2.0
		cardinal-components-base: Cardinal Components API (base) 2.5.4
		cardinal-components-block: Cardinal Components API (blocks) 2.5.4
		cardinal-components-chunk: Cardinal Components API (chunks) 2.5.4
		cardinal-components-entity: Cardinal Components API (entities) 2.5.4
		cardinal-components-item: Cardinal Components API (items) 2.5.4
		cardinal-components-level: Cardinal Components API (world saves) 2.5.4
		cardinal-components-util: Cardinal Components API (utilities) 2.5.4
		cardinal-components-world: Cardinal Components API (worlds) 2.5.4
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.4.5
		cloth-config2: Cloth Config v4 4.8.1
		cloth-datagen-api-v1: Cloth Datagen v1 1.4.6
		cloth-durability-bar-api-v1: Cloth Durability Bar API v1 1.4.6
		cloth-dynamic-registry-api-v1: Cloth Dynamic Registry API v1 1.4.6
		fabric: Fabric API 0.19.0+build.398-1.16
		fabric-api-base: Fabric API Base 0.1.3+12a8474cfa
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea894e
		fabric-command-api-v1: Fabric Command API (v1) 1.0.8+5ce533984e
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+52d308364e
		fabric-containers-v0: Fabric Containers (v0) 0.1.8+045df74f4e
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.9+059ea8664e
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d4e
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.0+e2e6cdad4e
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5b4e
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.1+91555cd14e
		fabric-item-api-v1: Fabric Item API (v1) 1.1.0+29679fd64e
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.0+438f96364e
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+730711c64e
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+3fa9f7c54e
		fabric-language-kotlin: Fabric Language Kotlin 1.3.72+build.1
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+74cc3b204e
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.0+fac8f3664e
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce994e
		fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d64e
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7b4e
		fabric-networking-v0: Fabric Networking (v0) 0.1.10+e00ecb5f4e
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.6.0+e81ec80b4e
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.6.1+ba4afa574e
		fabric-particles-v1: fabric-particles-v1 0.2.1+0a6f2a704e
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.4.3+e5d3217f4e
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.2.13+eae12eb84e
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.3.4+5d32f5834e
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.1.0+e2862de64e
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d4e
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.10+e5d3217f4e
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+534104904e
		fabric-rendering-v1: Fabric Rendering (v1) 1.2.0+fc24ff244e
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.2.9+e5d3217f4e
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+872498414e
		fabric-structure-api-v1: Fabric Structure API (v1) 1.0.0+516ece7c4e
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.0.3+ac8e8c594e
		fabric-textures-v0: Fabric Textures (v0) 1.0.4+eae12eb84e
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.2+ccce563e4e
		fabricloader: Fabric Loader 0.9.2+build.206
		fermion: Fermion 2.1.191
		fermion-modkeys: Fermion Modifier Keys 1.8.180-snapshot
		fiber: fiber 0.23.0-1
		libblockattributes_core: LibBlockAttributes (Core) 0.8.2-pre.1
		libblockattributes_fluids: LibBlockAttributes (Fluids) 0.8.2-pre.1
		libblockattributes_items: LibBlockAttributes (Items) 0.8.2-pre.1
		libstructure: LibStructure 1.5
		magna: Magna 1.4.0-1.16.2
		minecraft: Minecraft 1.16.2
		modmenu: Mod Menu 1.14.6+build.31
		org_jetbrains_annotations: annotations 17.0.0
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.3.72
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.3.72
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.3.72
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.3.72
		org_jetbrains_kotlinx_kotlinx-coroutines-core: kotlinx-coroutines-core 1.3.7
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.3.7
		org_joml_joml: joml 1.9.25
		patchouli: Patchouli 1.16-40-FABRIC
		roughlyenoughitems: Roughly Enough Items 5.2.10
		roughlyenoughitems-api: REI (API) 5.2.10
		roughlyenoughitems-default-plugin: REI (Default Plugin) 5.2.10
		roughlyenoughitems-runtime: REI (Runtime) 5.2.10
		shapes: Shapes 2.0.0+build.10
		team_reborn_energy: Energy 0.1.0
		wrenchable: Wrenchable 1.0.0+1.16.1
	Patchouli open book context: n/a
	Launched Version: MultiMC5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: AMD RAVEN (DRM 3.39.0, 5.9.0-rc2, LLVM 9.0.1) GL version 4.6 (Compatibility Profile) Mesa 20.1.6, X.Org
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, file/Unity-1.16.X-Base-2.3.1.zip (incompatible), file/Unity-1.16.X-Modded-1.2.0.zip (incompatible)
	Current Language: English (US)
	CPU: 8x AMD Ryzen 5 PRO 3400GE w/ Radeon Vega Graphics
#@!@# Game crashed! Crash report saved to: #@!@# /home/pbb/.multimc/instances/PBBTechPack 1.16.2 v1.1.0/.minecraft/crash-reports/crash-2020-09-06_12.47.30-client.txt
AL lib: (EE) alc_cleanup: 1 device not closed
Process exited with code 255.
```
  
</details>

**Comment by ghost** [comment]
This does not happen with Astromine 1.9.0+fabric-1.16.2 and earlier.

**Comment by shedaniel** [comment]
It is an issue that we are bundling the wrong version of fabric language kotlin, can you try to install a newer version yourself at the mean time? this will be fixed in the next update.

**Comment by ghost** [comment]
That works fine, thanks for the hint! Another mod I was using did not work with this new version of Fabric Language Kotline, so I opened a suggestion to support that there.

**Comment by vini2003** [comment]
Solved.
