### ISSUE TITLE
Various errors.

### ISSUE THREAD

**Issue by K0-RR** [Chainmail-Studios/Astromine#397]
![image](https://user-images.githubusercontent.com/43277609/110205631-6674b800-7e79-11eb-9ce7-3094b27bd1af.png)

I only use Astromine Core and Foundations and I don't know if this error shows up when using the full jar. I'm reporting this here because on the curseforge pages for Core and Foundations the Files are outdated so I downloaded the full jar and extracted them from it.

[main/ERROR]: Error while loading contents for book astromine-core:manual
java.lang.RuntimeException: Error building entry astromine-core:world/ore_clusters
	at Not Enough Crashes deobfuscated stack trace.(1.16.5+build.5) ~[?:?]
	at vazkii.patchouli.client.book.BookContents.lambda$reload$5(BookContents.java:142) ~[fb7f677c-a69b-4735-aa2f-a1ed00ffa579.jar:?]
	at java.util.HashMap$Values.forEach(HashMap.java:981) ~[?:1.8.0_275]
	at vazkii.patchouli.client.book.BookContents.reload(BookContents.java:138) ~[fb7f677c-a69b-4735-aa2f-a1ed00ffa579.jar:?]
	at vazkii.patchouli.common.book.Book.reloadContents(Book.java:183) ~[fb7f677c-a69b-4735-aa2f-a1ed00ffa579.jar:?]
	at java.util.HashMap$Values.forEach(HashMap.java:981) ~[?:1.8.0_275]
	at vazkii.patchouli.common.book.BookRegistry.reloadContents(BookRegistry.java:97) ~[fb7f677c-a69b-4735-aa2f-a1ed00ffa579.jar:?]
	at vazkii.patchouli.client.book.ClientBookRegistry.reload(ClientBookRegistry.java:63) ~[fb7f677c-a69b-4735-aa2f-a1ed00ffa579.jar:?]
	at vazkii.patchouli.client.base.ClientAdvancements.onClientPacket(ClientAdvancements.java:35) ~[fb7f677c-a69b-4735-aa2f-a1ed00ffa579.jar:?]
	at net.minecraft.client.network.ClientAdvancementManager.handler$bfe000$patchouli_onSync(ClientAdvancementManager:518) ~[?:?]
	at net.minecraft.client.network.ClientAdvancementManager.onAdvancements(ClientAdvancementManager:57) ~[?:?]
	at net.minecraft.client.network.ClientPlayNetworkHandler.onAdvancements(ClientPlayNetworkHandler:1358) ~[?:?]
	at net.minecraft.network.packet.s2c.play.AdvancementUpdateS2CPacket.apply(AdvancementUpdateS2CPacket:37) ~[?:?]
	at net.minecraft.network.packet.s2c.play.AdvancementUpdateS2CPacket.apply(AdvancementUpdateS2CPacket:16) ~[?:?]
	at net.minecraft.network.NetworkThreadUtils.method_11072(NetworkThreadUtils:21) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor:144) ~[?:?]
	at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor:23) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor:118) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor:103) ~[?:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1015) ~[?:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:681) ~[?:?]
	at net.minecraft.client.main.Main.main(Main:215) [intermediary-minecraft-1.16.5-client.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_275]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_275]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_275]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_275]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226) [fabric-loader-0.11.2.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146) [fabric-loader-0.11.2.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.2.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_275]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_275]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_275]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_275]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.lang.IllegalArgumentException: Template astromine:triturating does not exist
	at vazkii.patchouli.client.book.template.BookTemplate.createTemplate(BookTemplate.java:67) ~[fb7f677c-a69b-4735-aa2f-a1ed00ffa579.jar:?]
	at vazkii.patchouli.client.book.page.PageTemplate.canAdd(PageTemplate.java:47) ~[fb7f677c-a69b-4735-aa2f-a1ed00ffa579.jar:?]
	at vazkii.patchouli.client.book.BookEntry.build(BookEntry.java:219) ~[fb7f677c-a69b-4735-aa2f-a1ed00ffa579.jar:?]
	at vazkii.patchouli.client.book.BookContents.lambda$reload$5(BookContents.java:140) ~[fb7f677c-a69b-4735-aa2f-a1ed00ffa579.jar:?]
	... 35 more

**Comment by K0-RR** [comment]
[main/WARN]: @ModifyVariable(@At("INVOKE")) Shift.BY=2 on astromine.mixins.json:BiomeLayerSamplerMixin::localvar$zli000$modifyBiome exceeds the maximum allowed value: 0. Increase the value of maxShiftBy to suppress this warning.

**Comment by vini2003** [comment]
Fixed in development builds.
