### ISSUE TITLE
Chunk Corruption

### ISSUE THREAD

**Issue by KingGh0st** [Chainmail-Studios/Astromine#402]
The first time i started using the astromine in this world, when i put a lot of coal in the solid generator with the triturator i let it work  because it had to process the metite. When i went back to the triturator it kicked me off the server, but the server didn't crash, later when I looked at the console i saw this error:
[22:49:36] [IO-Worker-35/ERROR]: Failed to store chunk [-65, 12]
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2520.method_10711()" because "?" is null
	at net.minecraft.class_2487.method_10555(class_2487.java:451) ~[intermediary-server.jar:?]
	at net.minecraft.class_2487.method_10713(class_2487.java:116) ~[intermediary-server.jar:?]
	at net.minecraft.class_2487.method_10555(class_2487.java:458) ~[intermediary-server.jar:?]
	at net.minecraft.class_2487.method_10713(class_2487.java:116) ~[intermediary-server.jar:?]
	at net.minecraft.class_2487.method_10555(class_2487.java:458) ~[intermediary-server.jar:?]
	at net.minecraft.class_2487.method_10713(class_2487.java:116) ~[intermediary-server.jar:?]
	at net.minecraft.class_2487.method_10555(class_2487.java:458) ~[intermediary-server.jar:?]
	at net.minecraft.class_2487.method_10713(class_2487.java:116) ~[intermediary-server.jar:?]
	at net.minecraft.class_2499.method_10713(class_2499.java:91) ~[intermediary-server.jar:?]
	at net.minecraft.class_2487.method_10555(class_2487.java:458) ~[intermediary-server.jar:?]
	at net.minecraft.class_2487.method_10713(class_2487.java:116) ~[intermediary-server.jar:?]
	at net.minecraft.class_2487.method_10555(class_2487.java:458) ~[intermediary-server.jar:?]
	at net.minecraft.class_2487.method_10713(class_2487.java:116) ~[intermediary-server.jar:?]
	at net.minecraft.class_2507.method_10631(class_2507.java:95) ~[intermediary-server.jar:?]
	at net.minecraft.class_2507.method_10628(class_2507.java:83) ~[intermediary-server.jar:?]
	at net.minecraft.class_2867.method_23726(class_2867.java:63) ~[intermediary-server.jar:?]
	at net.minecraft.class_4698.method_23701(class_4698.java:144) ~[intermediary-server.jar:?]
	at net.minecraft.class_4698.method_23719(class_4698.java:134) ~[intermediary-server.jar:?]
	at net.minecraft.class_3847$class_3907.run(class_3847.java:54) [intermediary-server.jar:?]
	at net.minecraft.class_3846.method_16907(class_3846.java:94) [intermediary-server.jar:?]
	at net.minecraft.class_3846.method_16900(class_3846.java:137) [intermediary-server.jar:?]
	at net.minecraft.class_3846.run(class_3846.java:105) [intermediary-server.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]
[22:49:36] [IO-Worker-34/ERROR]: Failed to store chunk [-66, 13]
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2520.method_10711()" because "?" is null
	at net.minecraft.class_2487.method_10555(class_2487.java:451) ~[intermediary-server.jar:?]
	at net.minecraft.class_2487.method_10713(class_2487.java:116) ~[intermediary-server.jar:?]
	at net.minecraft.class_2487.method_10555(class_2487.java:458) ~[intermediary-server.jar:?]
	at net.minecraft.class_2487.method_10713(class_2487.java:116) ~[intermediary-server.jar:?]
	at net.minecraft.class_2487.method_10555(class_2487.java:458) ~[intermediary-server.jar:?]
	at net.minecraft.class_2487.method_10713(class_2487.java:116) ~[intermediary-server.jar:?]
	at net.minecraft.class_2487.method_10555(class_2487.java:458) ~[intermediary-server.jar:?]
	at net.minecraft.class_2487.method_10713(class_2487.java:116) ~[intermediary-server.jar:?]
	at net.minecraft.class_2487.method_10555(class_2487.java:458) ~[intermediary-server.jar:?]
	at net.minecraft.class_2487.method_10713(class_2487.java:116) ~[intermediary-server.jar:?]
	at net.minecraft.class_2499.method_10713(class_2499.java:91) ~[intermediary-server.jar:?]
	at net.minecraft.class_2487.method_10555(class_2487.java:458) ~[intermediary-server.jar:?]
	at net.minecraft.class_2487.method_10713(class_2487.java:116) ~[intermediary-server.jar:?]
	at net.minecraft.class_2487.method_10555(class_2487.java:458) ~[intermediary-server.jar:?]
	at net.minecraft.class_2487.method_10713(class_2487.java:116) ~[intermediary-server.jar:?]
	at net.minecraft.class_2507.method_10631(class_2507.java:95) ~[intermediary-server.jar:?]
	at net.minecraft.class_2507.method_10628(class_2507.java:83) ~[intermediary-server.jar:?]
	at net.minecraft.class_2867.method_23726(class_2867.java:63) ~[intermediary-server.jar:?]
	at net.minecraft.class_4698.method_23701(class_4698.java:144) ~[intermediary-server.jar:?]
	at net.minecraft.class_4698.method_23719(class_4698.java:134) ~[intermediary-server.jar:?]
	at net.minecraft.class_3847$class_3907.run(class_3847.java:54) [intermediary-server.jar:?]
	at net.minecraft.class_3846.method_16907(class_3846.java:94) [intermediary-server.jar:?]
	at net.minecraft.class_3846.method_16900(class_3846.java:137) [intermediary-server.jar:?]
	at net.minecraft.class_3846.run(class_3846.java:105) [intermediary-server.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]

(In those two chunks were the machines)
When i logged into the server again and tried to break the solid generator, the server crashed.

[23:40:13] [Server thread/FATAL]: Error executing task on Server
java.lang.NullPointerException: null
	at com.google.common.collect.Maps$7.transformEntry(Maps.java:2029) ~[server.jar:?]
	at com.google.common.collect.Maps$10.getValue(Maps.java:2074) ~[server.jar:?]
	at java.util.HashMap.putMapEntries(HashMap.java:515) ~[?:?]
	at java.util.HashMap.<init>(HashMap.java:486) ~[?:?]
	at com.google.common.collect.Maps.newHashMap(Maps.java:333) ~[server.jar:?]
	at net.minecraft.class_2487.method_10553(class_2487.java:432) ~[intermediary-server.jar:?]
	at net.minecraft.class_2487.method_10707(class_2487.java:32) ~[intermediary-server.jar:?]
	at com.google.common.collect.Maps$7.transformEntry(Maps.java:2029) ~[server.jar:?]
	at com.google.common.collect.Maps$10.getValue(Maps.java:2074) ~[server.jar:?]
	at java.util.HashMap.putMapEntries(HashMap.java:515) ~[?:?]
	at java.util.HashMap.<init>(HashMap.java:486) ~[?:?]
	at com.google.common.collect.Maps.newHashMap(Maps.java:333) ~[server.jar:?]
	at net.minecraft.class_2487.method_10553(class_2487.java:432) ~[intermediary-server.jar:?]
	at net.minecraft.class_2487.method_10707(class_2487.java:32) ~[intermediary-server.jar:?]
	at com.google.common.collect.Maps$7.transformEntry(Maps.java:2029) ~[server.jar:?]
	at com.google.common.collect.Maps$10.getValue(Maps.java:2074) ~[server.jar:?]
	at java.util.HashMap.putMapEntries(HashMap.java:515) ~[?:?]
	at java.util.HashMap.<init>(HashMap.java:486) ~[?:?]
	at com.google.common.collect.Maps.newHashMap(Maps.java:333) ~[server.jar:?]
	at net.minecraft.class_2487.method_10553(class_2487.java:432) ~[intermediary-server.jar:?]
	at net.minecraft.class_2487.method_10707(class_2487.java:32) ~[intermediary-server.jar:?]
	at com.google.common.collect.Maps$7.transformEntry(Maps.java:2029) ~[server.jar:?]
	at com.google.common.collect.Maps$10.getValue(Maps.java:2074) ~[server.jar:?]
	at java.util.HashMap.putMapEntries(HashMap.java:515) ~[?:?]
	at java.util.HashMap.<init>(HashMap.java:486) ~[?:?]
	at com.google.common.collect.Maps.newHashMap(Maps.java:333) ~[server.jar:?]
	at net.minecraft.class_2487.method_10553(class_2487.java:432) ~[intermediary-server.jar:?]
	at net.minecraft.class_1799.method_7972(class_1799.java:373) ~[intermediary-server.jar:?]
	at net.minecraft.class_2943$17.method_12732(class_2943.java:147) ~[intermediary-server.jar:?]
	at net.minecraft.class_2943$17.method_12714(class_2943.java:134) ~[intermediary-server.jar:?]
	at net.minecraft.class_2945$class_2946.method_12798(class_2945.java:292) ~[intermediary-server.jar:?]
	at net.minecraft.class_2945.method_12793(class_2945.java:179) ~[intermediary-server.jar:?]
	at net.minecraft.class_2739.<init>(class_2739.java:21) ~[intermediary-server.jar:?]
	at net.minecraft.class_3231.method_18757(class_3231.java:229) ~[intermediary-server.jar:?]
	at net.minecraft.class_3231.method_18760(class_3231.java:214) ~[intermediary-server.jar:?]
	at net.minecraft.class_3898$class_3208.method_18736(class_3898.java:1238) ~[intermediary-server.jar:?]
	at net.minecraft.class_3898$class_3208.method_18729(class_3898.java:1265) ~[intermediary-server.jar:?]
	at net.minecraft.class_3898.method_18701(class_3898.java:1020) ~[intermediary-server.jar:?]
	at net.minecraft.class_3215.method_18755(class_3215.java:477) ~[intermediary-server.jar:?]
	at net.minecraft.class_3218.method_18778(class_3218.java:933) ~[intermediary-server.jar:?]
	at net.minecraft.class_3218.method_14175(class_3218.java:835) ~[intermediary-server.jar:?]
	at net.minecraft.class_3218.method_8649(class_3218.java:765) ~[intermediary-server.jar:?]
	at net.minecraft.class_2248.method_9577(class_2248.java:367) ~[intermediary-server.jar:?]
	at net.minecraft.class_2248.method_9544(class_2248.java:351) ~[intermediary-server.jar:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at net.minecraft.class_2248.method_9511(class_2248.java:351) ~[intermediary-server.jar:?]
	at net.minecraft.class_2248.method_9556(class_2248.java:402) ~[intermediary-server.jar:?]
	at net.minecraft.class_3225.method_14266(class_3225.java:268) ~[intermediary-server.jar:?]
	at net.minecraft.class_3225.method_21717(class_3225.java:222) ~[intermediary-server.jar:?]
	at net.minecraft.class_3225.method_14263(class_3225.java:197) ~[intermediary-server.jar:?]
	at net.minecraft.class_3244.method_12066(class_3244.java:1008) ~[intermediary-server.jar:?]
	at net.minecraft.class_2846.method_12361(class_2846.java:40) ~[intermediary-server.jar:?]
	at net.minecraft.class_2846.method_11054(class_2846.java:10) ~[intermediary-server.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[intermediary-server.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[intermediary-server.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:144) ~[intermediary-server.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:761) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:155) ~[intermediary-server.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:118) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:743) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:737) ~[intermediary-server.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:127) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:722) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:674) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[intermediary-server.jar:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]
[23:40:13] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.class_148: Exception ticking world
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875) ~[intermediary-server.jar:?]
	at net.minecraft.class_3176.method_3813(class_3176.java:312) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:811) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[intermediary-server.jar:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: java.lang.NullPointerException
	at com.google.common.collect.Maps$7.transformEntry(Maps.java:2029) ~[server.jar:?]
	at com.google.common.collect.Maps$10.getValue(Maps.java:2074) ~[server.jar:?]
	at java.util.HashMap.putMapEntries(HashMap.java:515) ~[?:?]
	at java.util.HashMap.<init>(HashMap.java:486) ~[?:?]
	at com.google.common.collect.Maps.newHashMap(Maps.java:333) ~[server.jar:?]
	at net.minecraft.class_2487.method_10553(class_2487.java:432) ~[intermediary-server.jar:?]
	at net.minecraft.class_2487.method_10707(class_2487.java:32) ~[intermediary-server.jar:?]
	at com.google.common.collect.Maps$7.transformEntry(Maps.java:2029) ~[server.jar:?]
	at com.google.common.collect.Maps$10.getValue(Maps.java:2074) ~[server.jar:?]
	at java.util.HashMap.putMapEntries(HashMap.java:515) ~[?:?]
	at java.util.HashMap.<init>(HashMap.java:486) ~[?:?]
	at com.google.common.collect.Maps.newHashMap(Maps.java:333) ~[server.jar:?]
	at net.minecraft.class_2487.method_10553(class_2487.java:432) ~[intermediary-server.jar:?]
	at net.minecraft.class_2487.method_10707(class_2487.java:32) ~[intermediary-server.jar:?]
	at com.google.common.collect.Maps$7.transformEntry(Maps.java:2029) ~[server.jar:?]
	at com.google.common.collect.Maps$10.getValue(Maps.java:2074) ~[server.jar:?]
	at java.util.HashMap.putMapEntries(HashMap.java:515) ~[?:?]
	at java.util.HashMap.<init>(HashMap.java:486) ~[?:?]
	at com.google.common.collect.Maps.newHashMap(Maps.java:333) ~[server.jar:?]
	at net.minecraft.class_2487.method_10553(class_2487.java:432) ~[intermediary-server.jar:?]
	at net.minecraft.class_2487.method_10707(class_2487.java:32) ~[intermediary-server.jar:?]
	at com.google.common.collect.Maps$7.transformEntry(Maps.java:2029) ~[server.jar:?]
	at com.google.common.collect.Maps$10.getValue(Maps.java:2074) ~[server.jar:?]
	at java.util.HashMap.putMapEntries(HashMap.java:515) ~[?:?]
	at java.util.HashMap.<init>(HashMap.java:486) ~[?:?]
	at com.google.common.collect.Maps.newHashMap(Maps.java:333) ~[server.jar:?]
	at net.minecraft.class_2487.method_10553(class_2487.java:432) ~[intermediary-server.jar:?]
	at net.minecraft.class_1799.method_7972(class_1799.java:373) ~[intermediary-server.jar:?]
	at net.minecraft.class_2943$17.method_12732(class_2943.java:147) ~[intermediary-server.jar:?]
	at net.minecraft.class_2943$17.method_12714(class_2943.java:134) ~[intermediary-server.jar:?]
	at net.minecraft.class_2945$class_2946.method_12798(class_2945.java:292) ~[intermediary-server.jar:?]
	at net.minecraft.class_2945.method_12781(class_2945.java:160) ~[intermediary-server.jar:?]
	at net.minecraft.class_2739.<init>(class_2739.java:24) ~[intermediary-server.jar:?]
	at net.minecraft.class_3231.method_14306(class_3231.java:291) ~[intermediary-server.jar:?]
	at net.minecraft.class_3231.method_18756(class_3231.java:179) ~[intermediary-server.jar:?]
	at net.minecraft.class_3898.method_18727(class_3898.java:1065) ~[intermediary-server.jar:?]
	at net.minecraft.class_3215.method_14161(class_3215.java:402) ~[intermediary-server.jar:?]
	at net.minecraft.class_3215.method_12127(class_3215.java:337) ~[intermediary-server.jar:?]
	at net.minecraft.class_3218.method_18765(class_3218.java:353) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:871) ~[intermediary-server.jar:?]
	... 5 more

**here I put the crash report**
[crash-2021-03-09_23.40.13-server.txt](https://github.com/Mixinors/Astromine/files/6112901/crash-2021-03-09_23.40.13-server.txt)

**Comment by KingGh0st** [comment]
I think the problem is with the astromine, since it was the only mod that crashed, but it is probably an incompatibility

**Comment by vini2003** [comment]
Ultimately, this does not point to any specific error. Therefore, I'm unable to pinpoint the cause, or how to fix this - or if it's even Astromine-related.
