### ISSUE TITLE
Crashing while making a New World

### ISSUE THREAD

**Issue by Bismarck0523** [Chainmail-Studios/Astromine#403]
So I've wanted to try the mod, but every time I ltry to create a new world it says "Saving World" then crashes to the Minecraft Launcher with an Error code of 0.

Here's the crash report:
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 3/10/21 7:18 PM
Description: mouseClicked event handler

java.lang.ExceptionInInitializerError
	at virtuoel.pehkui.server.command.ScaleCommand.register(ScaleCommand.java:236)
	at virtuoel.pehkui.Pehkui.lambda$onInitialize$0(Pehkui.java:47)
	at virtuoel.pehkui.Pehkui$$Lambda$3174/116491049.register(Unknown Source)
	at net.fabricmc.fabric.api.command.v1.CommandRegistrationCallback.lambda$static$0(CommandRegistrationCallback.java:41)
	at net.fabricmc.fabric.api.command.v1.CommandRegistrationCallback$$Lambda$2578/1455948476.register(Unknown Source)
	at net.minecraft.class_2170.handler$zkd000$fabric_addCommands(class_2170.java:547)
	at net.minecraft.class_2170.<init>(class_2170.java:233)
	at net.minecraft.class_5350.<init>(class_5350.java:34)
	at net.minecraft.class_5350.method_29466(class_5350.java:78)
	at net.minecraft.class_310.method_29604(class_310.java:1956)
	at net.minecraft.class_310.method_29610(class_310.java:1808)
	at net.minecraft.class_310.method_29607(class_310.java:1752)
	at net.minecraft.class_525.method_2736(class_525.java:298)
	at net.minecraft.class_525.method_19922(class_525.java:238)
	at net.minecraft.class_525$$Lambda$5029/2135203084.onPress(Unknown Source)
	at net.minecraft.class_4185.method_25306(class_4185.java:33)
	at net.minecraft.class_4264.method_25348(class_4264.java:16)
	at net.minecraft.class_339.method_25402(class_339.java:149)
	at net.minecraft.class_4069.method_25402(class_4069.java:27)
	at net.minecraft.class_312.method_1611(class_312.java:92)
	at net.minecraft.class_312$$Lambda$4900/14261942.run(Unknown Source)
	at net.minecraft.class_437.method_25412(class_437.java:435)
	at net.minecraft.class_312.method_1601(class_312.java:92)
	at net.minecraft.class_312.method_22686(class_312.java:162)
	at net.minecraft.class_312$$Lambda$4899/293659205.run(Unknown Source)
	at net.minecraft.class_1255.execute(class_1255.java:94)
	at net.minecraft.class_312.method_22684(class_312.java:162)
	at net.minecraft.class_312$$Lambda$4047/23440369.invoke(Unknown Source)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:127)
	at net.minecraft.class_310.method_1523(class_310.java:1071)
	at net.minecraft.class_310.method_1514(class_310.java:681)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
Caused by: java.lang.NullPointerException
	at virtuoel.pehkui.server.command.arguments.ScaleModifierArgumentType$$Lambda$5633/1595591093.apply(Unknown Source)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at virtuoel.pehkui.server.command.arguments.ScaleModifierArgumentType.<clinit>(ScaleModifierArgumentType.java:26)
	... 42 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at virtuoel.pehkui.server.command.ScaleCommand.register(ScaleCommand.java:236)
	at virtuoel.pehkui.Pehkui.lambda$onInitialize$0(Pehkui.java:47)
	at virtuoel.pehkui.Pehkui$$Lambda$3174/116491049.register(Unknown Source)
	at net.fabricmc.fabric.api.command.v1.CommandRegistrationCallback.lambda$static$0(CommandRegistrationCallback.java:41)
	at net.fabricmc.fabric.api.command.v1.CommandRegistrationCallback$$Lambda$2578/1455948476.register(Unknown Source)
	at net.minecraft.class_2170.handler$zkd000$fabric_addCommands(class_2170.java:547)
	at net.minecraft.class_2170.<init>(class_2170.java:233)
	at net.minecraft.class_5350.<init>(class_5350.java:34)
	at net.minecraft.class_5350.method_29466(class_5350.java:78)
	at net.minecraft.class_310.method_29604(class_310.java:1956)
	at net.minecraft.class_310.method_29610(class_310.java:1808)
	at net.minecraft.class_310.method_29607(class_310.java:1752)
	at net.minecraft.class_525.method_2736(class_525.java:298)
	at net.minecraft.class_525.method_19922(class_525.java:238)
	at net.minecraft.class_525$$Lambda$5029/2135203084.onPress(Unknown Source)
	at net.minecraft.class_4185.method_25306(class_4185.java:33)
	at net.minecraft.class_4264.method_25348(class_4264.java:16)
	at net.minecraft.class_339.method_25402(class_339.java:149)
	at net.minecraft.class_4069.method_25402(class_4069.java:27)
	at net.minecraft.class_312.method_1611(class_312.java:92)
	at net.minecraft.class_312$$Lambda$4900/14261942.run(Unknown Source)

-- Affected screen --
Details:
	Screen name: net.minecraft.class_525
Stacktrace:
	at net.minecraft.class_437.method_25412(class_437.java:435)
	at net.minecraft.class_312.method_1601(class_312.java:92)
	at net.minecraft.class_312.method_22686(class_312.java:162)
	at net.minecraft.class_312$$Lambda$4899/293659205.run(Unknown Source)
	at net.minecraft.class_1255.execute(class_1255.java:94)
	at net.minecraft.class_312.method_22684(class_312.java:162)
	at net.minecraft.class_312$$Lambda$4047/23440369.invoke(Unknown Source)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:127)
	at net.minecraft.class_310.method_1523(class_310.java:1071)
	at net.minecraft.class_310.method_1514(class_310.java:681)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1314475176 bytes (1253 MB) / 1979711488 bytes (1888 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 16
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		appleskin: AppleSkin 1.0.11
		astromine: Astromine 1.11.5+fabric-1.16.5
		astromine-core: Astromine: Core 1.11.5+fabric-1.16.5
		astromine-discoveries: Astromine: Discoveries 1.11.5+fabric-1.16.5
		astromine-foundations: Astromine: Foundations 1.11.5+fabric-1.16.5
		astromine-technologies: Astromine: Technologies 1.11.5+fabric-1.16.5
		astromine-transportations: Astromine: Transportations 1.11.5+fabric-1.16.5
		autoconfig1u: Auto Config v1 Updated 3.3.1
		blade: Blade 2.0.0
		blue_endless_jankson: jankson 1.2.0
		cardinal-components-base: Cardinal Components API (base) 2.7.10
		cardinal-components-block: Cardinal Components API (blocks) 2.7.10
		cardinal-components-chunk: Cardinal Components API (chunks) 2.7.10
		cardinal-components-entity: Cardinal Components API (entities) 2.7.10
		cardinal-components-item: Cardinal Components API (items) 2.7.10
		cardinal-components-level: Cardinal Components API (world saves) 2.7.10
		cardinal-components-util: Cardinal Components API (utilities) 2.7.10
		cardinal-components-world: Cardinal Components API (worlds) 2.7.10
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.5.47
		cloth-config2: Cloth Config v4 4.11.14
		cloth-datagen-api-v1: Cloth Datagen v1 1.4.9
		cloth-durability-bar-api-v1: Cloth Durability Bar API v1 1.4.9
		craftpresence: CraftPresence 1.7.6
		diggusmaximus: Diggus Maximus 1.4.2-1.16.3
		enchant_giver: Enchant Giver 1.0.3
		extraorigins: Extra Origins 1.16.5-9
		fabric: Fabric API 0.32.0+1.16
		fabric-api-base: Fabric API Base 0.2.1+9354966b7d
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.0.0+dc716ea17d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.1+ca58154a7d
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+ca58154a7d
		fabric-command-api-v1: Fabric Command API (v1) 1.1.0+f9b3753b7d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+ca58154a7d
		fabric-containers-v0: Fabric Containers (v0) 0.1.11+9354966b7d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.1+ca58154a7d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+ca58154a7d
		fabric-dimensions-v1: fabric-dimensions-v1 2.0.6+9354966b7d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.0.3+ca58154a7d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.2+ca58154a7d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+ca58154a7d
		fabric-furnaces: Fabric Furnaces 1.3.3-1.16.4
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+ca58154a7d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.1+ca58154a7d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.3+ca58154a7d
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+9354966b7d
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.1+ca58154a7d
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.1+ca58154a7d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.2+ca58154a7d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+ca58154a7d
		fabric-models-v0: Fabric Models (v0) 0.2.1+ca58154a7d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.1+ca58154a7d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.8+ca58154a7d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+ca58154a7d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.4+9354966b7d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.2+ca58154a7d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+ca58154a7d
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.4+ca58154a7d
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.1+ca58154a7d
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.4+ca58154a7d
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.2.1+ca58154a7d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+ca58154a7d
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+ca58154a7d
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+ca58154a7d
		fabric-rendering-v1: Fabric Rendering (v1) 1.5.1+ca58154a7d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.2+ca58154a7d
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.0+c045166c7d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.5+9354966b7d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.4+ca58154a7d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.1+ca58154a7d
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+ca58154a7d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.6+ca58154a7d
		fabricloader: Fabric Loader 0.11.2
		fallflyinglib: FallFlyingLib 1.1.0
		fermion: Fermion 2.1.191
		fermion-modkeys: Fermion Modifier Keys 1.10.218
		fiber: fiber 0.23.0-2
		java: Java HotSpot(TM) 64-Bit Server VM 8
		kyrptconfig: Kytpt Config 1.1.4-1.16
		libblockattributes_core: LibBlockAttributes (Core) 0.8.5
		libblockattributes_fluids: LibBlockAttributes (Fluids) 0.8.5
		libblockattributes_items: LibBlockAttributes (Items) 0.8.5
		magna: Magna 1.4.3-1.16.2
		maybe-data: Maybe data 1.0.0-1.16.2
		mcda: MC Dungeons Armors 1.3.0
		mcdw: MC Dungeons Weapons 3.0.5
		minecraft: Minecraft 1.16.5
		modmenu: Mod Menu 1.16.8
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.4.0
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.4.0
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.4.0
		org_joml_joml: joml 1.10.0
		origins: Origins 0.6.1
		patchouli: Patchouli 1.16.4-48-FABRIC
		pehkui: Pehkui 1.8.0+21w08b
		piglib: Piglib 1.0.1
		reach-entity-attributes: Reach Entity Attribute 1.0.1
		roughlyenoughitems: Roughly Enough Items 5.10.184
		roughlyenoughitems-api: REI (API) 5.10.184
		roughlyenoughitems-default-plugin: REI (Default Plugin) 5.10.184
		roughlyenoughitems-runtime: REI (Runtime) 5.10.184
		roughlyenoughresources: Roughly Enough Resources 2.1.3
		team_reborn_energy: Energy 0.1.1
		terraform-shapes-api-v1: Terraform Shapes API (v1) 1.0.0+build.4
		waila: Hwyla 1.9.22
		wrenchable: Wrenchable 1.0.0+1.16.1
	Patchouli open book context: n/a
	Launched Version: fabric-loader-0.11.2-1.16.5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1660 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 461.72, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla
	Current Language: English (US)
	CPU: 16x AMD Ryzen 7 2700X Eight-Core Processor

**Comment by amusingimpala75** [comment]
> at virtuoel.pehkui.server.command.ScaleCommand.register(ScaleCommand.java:236)

It appears that the Pehkui mod is cauing the crash.

**Comment by Ueaj-Kerman** [comment]
this is pehuiki isue i think
