### ISSUE TITLE
Can't Start: "Failed to read accessWidener file from mod astromine-core" Help

### ISSUE THREAD

**Issue by MegaLP** [Chainmail-Studios/Astromine#422]
[20:51:53] [main/ERROR]: Uncaught exception in thread "main"
java.lang.RuntimeException: Failed to read accessWidener file from mod astromine-core
	at net.fabricmc.loader.impl.FabricLoaderImpl.loadAccessWideners(FabricLoaderImpl.java:478) ~[fabric-loader-0.12.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:145) ~[fabric-loader-0.12.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71) ~[fabric-loader-0.12.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.12.8.jar:?]
Caused by: net.fabricmc.accesswidener.AccessWidenerFormatException: Class-names must be specified as a/b/C, not a.b.C, but found: net/minecraft/com.github.chainmailstudios.astromine.technologies.client.particle/DefaultParticleType
	at net.fabricmc.accesswidener.AccessWidenerReader.error(AccessWidenerReader.java:281) ~[access-widener-2.0.1.jar:?]
	at net.fabricmc.accesswidener.AccessWidenerReader.validateClassName(AccessWidenerReader.java:287) ~[access-widener-2.0.1.jar:?]
	at net.fabricmc.accesswidener.AccessWidenerReader.handleClass(AccessWidenerReader.java:184) ~[access-widener-2.0.1.jar:?]
	at net.fabricmc.accesswidener.AccessWidenerReader.read(AccessWidenerReader.java:135) ~[access-widener-2.0.1.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.loadAccessWideners(FabricLoaderImpl.java:476) ~[fabric-loader-0.12.8.jar:?]
	... 3 more

**Comment by shedaniel** [comment]
E

**Comment by MegaLP** [comment]
> 

E?
what do you mean

**Comment by Ueaj-Kerman** [comment]
cope

**Comment by DistendedDev** [comment]
I had the same problem
