### ISSUE TITLE
Server crash on start (1.11.6)

### ISSUE THREAD

**Issue by alije123** [Chainmail-Studios/Astromine#426]
fabric-server-mc.1.16.5-loader.0.12.12-launcher.0.10.2

```
[02:46:05] [main/INFO]: Loading Minecraft 1.16.5 with Fabric Loader 0.12.12
[02:46:05] [main/WARN]: Warnings were found!
 - Mod 'Fabric Rendering Fluids (v1)' (fabric-rendering-fluids-v1) 0.1.15+3cc0f0907d recommends any version of fabric-textures-v0, which is disabled for this environment (client/server only)!
	 - You should install any version of fabric-textures-v0 for the optimal experience.
[02:46:05] [main/INFO]: Loading 75 mods:
	- astromine 1.11.6+fabric-1.16.5
	- astromine-core 1.11.+fabric-1.16.5 via astromine
	- astromine-discoveries 1.11.6+fabric-1.16.5 via astromine
	- astromine-foundations 1.11.6+fabric-1.16.5 via astromine
	- astromine-technologies 1.11.6+fabric-1.16.5 via astromine
	- astromine-transportations 1.11.6+fabric-1.16.5 via astromine
	- autoconfig1u 3.3.1 via astromine-core
	- blade 2.0.0 via astromine-core
	- cardinal-components-base 2.7.10 via astromine-core
	- cardinal-components-block 2.7.10 via astromine-core
	- cardinal-components-chunk 2.7.10 via astromine-core
	- cardinal-components-entity 2.7.10 via astromine-core
	- cardinal-components-item 2.7.10 via astromine-core
	- cardinal-components-level 2.7.10 via astromine-core
	- cardinal-components-util 2.7.10 via astromine-core
	- cardinal-components-world 2.7.10 via astromine-core
	- cloth-basic-math 0.5.1 via cloth-config2
	- cloth-config2 4.8.3 via astromine-core
	- cloth-datagen-api-v1 1.4.9 via astromine-core
	- cloth-durability-bar-api-v1 1.4.9 via astromine-core
	- fabric 0.42.0+1.16
	- fabric-api-base 0.4.0+3cc0f0907d via fabric
	- fabric-api-lookup-api-v1 1.3.1+3cc0f0907d via fabric
	- fabric-biome-api-v1 3.1.13+3cc0f0907d via fabric
	- fabric-command-api-v1 1.1.3+3cc0f0907d via fabric
	- fabric-commands-v0 0.2.3+3cc0f0907d via fabric
	- fabric-containers-v0 0.1.12+3cc0f0907d via fabric
	- fabric-content-registries-v0 0.2.5+3cc0f0907d via fabric
	- fabric-crash-report-info-v1 0.1.4+3cc0f0907d via fabric
	- fabric-dimensions-v1 2.0.8+3cc0f0907d via fabric
	- fabric-entity-events-v1 1.2.4+3cc0f0907d via fabric
	- fabric-events-interaction-v0 0.4.5+3cc0f0907d via fabric
	- fabric-events-lifecycle-v0 0.2.2+3cc0f0907d via fabric
	- fabric-game-rule-api-v1 1.0.7+3cc0f0907d via fabric
	- fabric-item-api-v1 1.2.2+3cc0f0907d via fabric
	- fabric-item-groups-v0 0.3.1+3cc0f0907d via fabric
	- fabric-lifecycle-events-v1 1.2.2+3cc0f0907d via fabric
	- fabric-loot-tables-v1 1.0.3+3cc0f0907d via fabric
	- fabric-mining-levels-v0 0.1.4+3cc0f0907d via fabric
	- fabric-networking-api-v1 1.0.5+3cc0f0907d via fabric
	- fabric-networking-blockentity-v0 0.2.9+3cc0f0907d via fabric
	- fabric-networking-v0 0.3.3+3cc0f0907d via fabric
	- fabric-object-builder-api-v1 1.9.6+3cc0f0907d via fabric
	- fabric-object-builders-v0 0.7.3+3cc0f0907d via fabric
	- fabric-particles-v1 0.2.5+3cc0f0907d via fabric
	- fabric-registry-sync-v0 0.7.6+3cc0f0907d via fabric
	- fabric-rendering-data-attachment-v1 0.1.6+3cc0f0907d via fabric
	- fabric-rendering-fluids-v1 0.1.15+3cc0f0907d via fabric
	- fabric-resource-loader-v0 0.4.8+3cc0f0907d via fabric
	- fabric-screen-handler-api-v1 1.1.6+3cc0f0907d via fabric
	- fabric-structure-api-v1 1.1.12+3cc0f0907d via fabric
	- fabric-tag-extensions-v0 1.1.2+3cc0f0907d via fabric
	- fabric-tool-attribute-api-v1 1.2.8+3cc0f0907d via fabric
	- fabric-transfer-api-v1 1.5.0+3cc0f0907d via fabric
	- fabricloader 0.12.12
	- fermion 2.1.191 via wrenchable
	- fermion-modkeys 1.10.218 via astromine-core
	- fiber 0.23.0-2 via patchouli
	- java 17
	- libblockattributes_core 0.8.5 via astromine-core
	- libblockattributes_fluids 0.8.5 via astromine-core
	- libblockattributes_items 0.8.5 via astromine-core
	- magna 1.4.3-1.16.2 via astromine-core
	- maybe-data 1.0.0-1.16.2 via astromine-core
	- minecraft 1.16.5
	- notenoughcrashes 4.1.4+1.16.5
	- org_jetbrains_kotlin_kotlin-stdlib 1.4.0 via astromine-core
	- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.4.0 via astromine-core
	- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.4.0 via astromine-core
	- org_joml_joml 1.10.0 via astromine-core
	- patchouli 1.16.4-48-FABRIC via astromine-core
	- piglib 1.0.1 via astromine-core
	- team_reborn_energy 0.1.1 via astromine-core
	- terraform-shapes-api-v1 1.0.0+build.4 via astromine-core
	- wrenchable 1.0.0+1.16.1 via astromine-core
[02:46:05] [main/WARN]: Mod `astromine-core` (1.11.+fabric-1.16.5) does not respect SemVer - comparison support is limited.
[02:46:05] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.4 Source=file:/D:/mine/libraries/net/fabricmc/sponge-mixin/0.10.7+mixin.0.8.4/sponge-mixin-0.10.7+mixin.0.8.4.jar Service=Knot/Fabric Env=SERVER
[02:46:05] [main/WARN]: Reference map 'astromine-foundations-refmap.json' for astromine-foundations.mixins.json could not be read. If this is a development environment you can ignore this message
[02:46:05] [main/WARN]: Reference map 'astromine-technologies-refmap.json' for astromine-technologies.mixins.json could not be read. If this is a development environment you can ignore this message
[02:46:05] [main/WARN]: Reference map 'astromine-transportations-refmap.json' for astromine-transportations.mixins.json could not be read. If this is a development environment you can ignore this message
[02:46:05] [main/WARN]: Reference map 'blade-2.0.0+fabric-1.16.3-refmap.json' for blade.mixins.json could not be read. If this is a development environment you can ignore this message
[02:46:06] [main/WARN]: Reference map 'wrenchable-refmap.json' for wrenchable.mixins.json could not be read. If this is a development environment you can ignore this message
[02:46:14] [main/INFO]: Silk not found, not loading compatibility for fluids.
[02:46:14] [main/INFO]: RebornCore not found, not loading compatibility for fluids. (reborncore.common.blockentity.MachineBaseBlockEntity)
[02:46:17] [main/WARN]: @ModifyVariable(@At("INVOKE")) Shift.BY=2 on astromine.mixins.json:BiomeLayerSamplerMixin::localvar$zzc000$modifyBiome exceeds the maximum allowed value: 0. Increase the value of maxShiftBy to suppress this warning.
[02:46:18] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[02:46:18] [main/INFO]: Found new data pack Fabric Mods, loading it automatically
[02:46:19] [main/WARN]: Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498]
[02:46:19] [main/WARN]: Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[02:46:19] [main/WARN]: Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]
[02:46:19] [main/WARN]: Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]
[02:46:19] [main/WARN]: Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[02:46:19] [main/INFO]: Reloading ResourceManager: Default, Fabric Mods (Astromine: Core, Astromine: Discoveries, Astromine: Foundations, Astromine: Technologies, Astromine: Transportations, Fabric Tool Attribute API (v1), Maybe data, Piglib)
[02:46:21] [Worker-Main-5/INFO]: Loaded 15 recipes
[02:46:21] [Worker-Main-5/WARN]: Datapack tried to redefine minecraft:empty loot table, ignoring
[02:46:22] [Worker-Main-5/INFO]: Loaded 1615 advancements
[02:46:22] [Worker-Main-5/INFO]: Loaded 1 conditional recipes
[02:46:27] [main/INFO]: Applied 87 biome modifications to 77 of 87 new biomes in 15.81 ms
[02:46:27] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.ExceptionInInitializerError
	at Not Enough Crashes deobfuscated stack trace.(1.16.5+build.10) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:610) ~[fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.12.12.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:66) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:64) [fabric-server-mc.1.16.5-loader.0.12.12-launcher.0.10.2.jar:0.10.2]
Caused by: java.lang.ExceptionInInitializerError
	at net.minecraft.world.level.LevelProperties.mdf198e5$lambda$static$0$0(LevelProperties:733) ~[?:?]
	at net.minecraft.util.Lazy.get(Lazy:16) ~[?:?]
	at net.minecraft.world.level.LevelProperties.handler$zcl000$initComponents(LevelProperties:739) ~[?:?]
	at net.minecraft.world.level.LevelProperties.<init>(LevelProperties:148) ~[?:?]
	at net.minecraft.world.level.LevelProperties.<init>(LevelProperties:151) ~[?:?]
	at net.minecraft.server.Main.redirect$zdm000$onCreateNewLevelProperties(Main:587) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main:169) ~[server-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608) ~[fabric-loader-0.12.12.jar:?]
	... 8 more
Caused by: java.lang.RuntimeException: Failed to hack fabric API
	at dev.onyxstudios.cca.internal.base.ComponentsInternals.<clinit>(ComponentsInternals.java:56) ~[cardinal-components-base-2.7.10-55c7b587fe0a5a0e.jar:?]
	at net.minecraft.world.level.LevelProperties.mdf198e5$lambda$static$0$0(LevelProperties:733) ~[?:?]
	at net.minecraft.util.Lazy.get(Lazy:16) ~[?:?]
	at net.minecraft.world.level.LevelProperties.handler$zcl000$initComponents(LevelProperties:739) ~[?:?]
	at net.minecraft.world.level.LevelProperties.<init>(LevelProperties:148) ~[?:?]
	at net.minecraft.world.level.LevelProperties.<init>(LevelProperties:151) ~[?:?]
	at net.minecraft.server.Main.redirect$zdm000$onCreateNewLevelProperties(Main:587) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main:169) ~[server-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608) ~[fabric-loader-0.12.12.jar:?]
	... 8 more
Caused by: java.lang.NoSuchFieldException: type
	at java.lang.Class.getDeclaredField(Class.java:2610) ~[?:?]
	at dev.onyxstudios.cca.internal.base.ComponentsInternals.<clinit>(ComponentsInternals.java:52) ~[cardinal-components-base-2.7.10-55c7b587fe0a5a0e.jar:?]
	at net.minecraft.world.level.LevelProperties.mdf198e5$lambda$static$0$0(LevelProperties:733) ~[?:?]
	at net.minecraft.util.Lazy.get(Lazy:16) ~[?:?]
	at net.minecraft.world.level.LevelProperties.handler$zcl000$initComponents(LevelProperties:739) ~[?:?]
	at net.minecraft.world.level.LevelProperties.<init>(LevelProperties:148) ~[?:?]
	at net.minecraft.world.level.LevelProperties.<init>(LevelProperties:151) ~[?:?]
	at net.minecraft.server.Main.redirect$zdm000$onCreateNewLevelProperties(Main:587) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main:169) ~[server-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608) ~[fabric-loader-0.12.12.jar:?]
	... 8 more
```

**Comment by whoooh** [comment]
🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕

**Comment by ghost** [comment]
Add [this](https://www.curseforge.com/minecraft/mc-mods/cardinal-components/files/3312678).

**Comment by shedaniel** [comment]
Marked that as a required dependency on CurseForge
