### ISSUE TITLE
Problems with catwalks Crash  when creating a new World

### ISSUE THREAD

**Issue by MegaLP** [Chainmail-Studios/Astromine#427]
Fabric Loader 0.13.1

[00:34:27] [main/FATAL]: Reported exception thrown!
net.minecraft.class_148: Starting integrated server
	at Not Enough Crashes deobfuscated stack trace.(1.16.5+build.10) ~[?:?]
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen:440) ~[?:?]
	at net.minecraft.client.Mouse.onMouseButton(Mouse:92) ~[?:?]
	at net.minecraft.client.Mouse.method_22686(Mouse:162) ~[?:?]
	at net.minecraft.class_312$$Lambda$8518/2071920442.run(Unknown Source) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor:94) ~[?:?]
	at net.minecraft.client.Mouse.method_22684(Mouse:162) ~[?:?]
	at net.minecraft.class_312$$Lambda$7697/767592530.invoke(Unknown Source) ~[?:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) ~[lwjgl-glfw-3.2.2.jar:build 10]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10]
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101) ~[lwjgl-glfw-3.2.2.jar:build 10]
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem:109) ~[client-intermediary.jar:?]
	at net.minecraft.client.util.Window.swapBuffers(Window:308) ~[?:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1068) ~[?:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:681) ~[?:?]
	at net.minecraft.client.main.Main.main(Main:215) [client-intermediary.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) [fabric-loader-0.13.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.13.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.13.1.jar:?]
Caused by: java.lang.NoSuchMethodError: com.zundrel.wrenchable.WrenchableUtilities.isWrench(Lnet/minecraft/class_1792;)Z
	at com.github.chainmailstudios.astromine.transportations.common.block.CatwalkBlock.getOutlineShape(CatwalkBlock.java:140) ~[astromine-transportations-1.11.6bric-1.16.5-98fe33e66b8d77ca.jar:?]
	at net.minecraft.block.AbstractBlock$AbstractBlockState.getOutlineShape(AbstractBlock:786) ~[?:?]
	at net.minecraft.block.AbstractBlock$AbstractBlockState.getOutlineShape(AbstractBlock:782) ~[?:?]
	at net.minecraft.block.Block.isTranslucent(Block:295) ~[?:?]
	at net.minecraft.block.AbstractBlock$AbstractBlockState$ShapeCache.<init>(AbstractBlock:1010) ~[?:?]
	at net.minecraft.block.AbstractBlock$AbstractBlockState$ShapeCache.<init>(AbstractBlock:994) ~[?:?]
	at net.minecraft.block.AbstractBlock$AbstractBlockState.initShapeCache(AbstractBlock:643) ~[?:?]
	at net.minecraft.class_2246$$Lambda$10099/1331156786.accept(Unknown Source) ~[?:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_51]
	at net.minecraft.block.Blocks.refreshShapeCache(Blocks:892) ~[?:?]
	at net.minecraft.tag.TagManager.apply(TagManager:24) ~[?:?]
	at net.minecraft.resource.ServerResourceManager.loadRegistryTags(ServerResourceManager:88) ~[?:?]
	at net.minecraft.client.MinecraftClient.startIntegratedServer(MinecraftClient:1842) ~[?:?]
	at net.minecraft.client.MinecraftClient.method_29609(MinecraftClient:1826) ~[?:?]
	at net.minecraft.class_310$$Lambda$10066/1143761119.run(Unknown Source) ~[?:?]
	at net.minecraft.client.MinecraftClient.method_29605(MinecraftClient:1927) ~[?:?]
	at net.minecraft.class_310$$Lambda$10067/215126238.accept(Unknown Source) ~[?:?]
	at net.minecraft.client.gui.screen.ConfirmScreen.method_19799(ConfirmScreen:41) ~[?:?]
	at net.minecraft.class_410$$Lambda$8612/1313037434.onPress(Unknown Source) ~[?:?]
	at net.minecraft.client.gui.widget.ButtonWidget.onPress(ButtonWidget:33) ~[?:?]
	at net.minecraft.client.gui.widget.PressableWidget.onClick(PressableWidget:16) ~[?:?]
	at net.minecraft.client.gui.widget.ClickableWidget.mouseClicked(ClickableWidget:149) ~[?:?]
	at net.minecraft.client.gui.ParentElement.mouseClicked(ParentElement:27) ~[?:?]
	at net.minecraft.client.Mouse.method_1611(Mouse:92) ~[?:?]
	at net.minecraft.class_312$$Lambda$8519/630583475.run(Unknown Source) ~[?:?]
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen:435) ~[?:?]
	... 21 more
[00:34:27] [main/FATAL]: Unreported exception thrown!
java.lang.NoSuchMethodError: com.zundrel.wrenchable.WrenchableUtilities.isWrench(Lnet/minecraft/class_1792;)Z
	at Not Enough Crashes deobfuscated stack trace.(1.16.5+build.10) ~[?:?]
	at com.github.chainmailstudios.astromine.transportations.common.block.CatwalkBlock.getOutlineShape(CatwalkBlock.java:140) ~[astromine-transportations-1.11.6bric-1.16.5-98fe33e66b8d77ca.jar:?]
	at net.minecraft.block.AbstractBlock$AbstractBlockState.getOutlineShape(AbstractBlock:786) ~[?:?]
	at net.minecraft.block.AbstractBlock$AbstractBlockState.getOutlineShape(AbstractBlock:782) ~[?:?]
	at net.minecraft.block.Block.isTranslucent(Block:295) ~[?:?]
	at net.minecraft.block.AbstractBlock$AbstractBlockState$ShapeCache.<init>(AbstractBlock:1010) ~[?:?]
	at net.minecraft.block.AbstractBlock$AbstractBlockState$ShapeCache.<init>(AbstractBlock:994) ~[?:?]
	at net.minecraft.block.AbstractBlock$AbstractBlockState.initShapeCache(AbstractBlock:643) ~[?:?]
	at net.minecraft.class_2246$$Lambda$10099/1331156786.accept(Unknown Source) ~[?:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_51]
	at net.minecraft.block.Blocks.refreshShapeCache(Blocks:892) ~[?:?]
	at net.minecraft.tag.TagManager.apply(TagManager:24) ~[?:?]
	at net.minecraft.resource.ServerResourceManager.loadRegistryTags(ServerResourceManager:88) ~[?:?]
	at net.minecraft.client.MinecraftClient.startIntegratedServer(MinecraftClient:1842) ~[?:?]
	at net.minecraft.client.MinecraftClient.method_29609(MinecraftClient:1826) ~[?:?]
	at net.minecraft.class_310$$Lambda$10066/1143761119.run(Unknown Source) ~[?:?]
	at net.minecraft.client.MinecraftClient.method_29605(MinecraftClient:1927) ~[?:?]
	at net.minecraft.class_310$$Lambda$10067/215126238.accept(Unknown Source) ~[?:?]
	at net.minecraft.client.gui.screen.ConfirmScreen.method_19799(ConfirmScreen:41) ~[?:?]
	at net.minecraft.class_410$$Lambda$8612/1313037434.onPress(Unknown Source) ~[?:?]
	at net.minecraft.client.gui.widget.ButtonWidget.onPress(ButtonWidget:33) ~[?:?]
	at net.minecraft.client.gui.widget.PressableWidget.onClick(PressableWidget:16) ~[?:?]
	at net.minecraft.client.gui.widget.ClickableWidget.mouseClicked(ClickableWidget:149) ~[?:?]
	at net.minecraft.client.gui.ParentElement.mouseClicked(ParentElement:27) ~[?:?]
	at net.minecraft.client.Mouse.method_1611(Mouse:92) ~[?:?]
	at net.minecraft.class_312$$Lambda$8519/630583475.run(Unknown Source) ~[?:?]
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen:435) ~[?:?]
	at net.minecraft.client.Mouse.onMouseButton(Mouse:92) ~[?:?]
	at net.minecraft.client.Mouse.method_22686(Mouse:162) ~[?:?]
	at net.minecraft.class_312$$Lambda$8518/2071920442.run(Unknown Source) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor:94) ~[?:?]
	at net.minecraft.client.Mouse.method_22684(Mouse:162) ~[?:?]
	at net.minecraft.class_312$$Lambda$7697/767592530.invoke(Unknown Source) ~[?:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) ~[lwjgl-glfw-3.2.2.jar:build 10]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10]
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101) ~[lwjgl-glfw-3.2.2.jar:build 10]
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem:109) ~[client-intermediary.jar:?]
	at net.minecraft.client.util.Window.swapBuffers(Window:308) ~[?:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1068) ~[?:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:681) ~[?:?]
	at net.minecraft.client.main.Main.main(Main:215) [client-intermediary.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) [fabric-loader-0.13.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.13.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.13.1.jar:?]
---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 2/7/22 12:34 AM
Description: Starting integrated server

java.lang.NoSuchMethodError: com.zundrel.wrenchable.WrenchableUtilities.isWrench(Lnet/minecraft/class_1792;)Z
	at Not Enough Crashes deobfuscated stack trace.(1.16.5+build.10)
	at com.github.chainmailstudios.astromine.transportations.common.block.CatwalkBlock.getOutlineShape(CatwalkBlock.java:140)
	at net.minecraft.block.AbstractBlock$AbstractBlockState.getOutlineShape(AbstractBlock:786)
	at net.minecraft.block.AbstractBlock$AbstractBlockState.getOutlineShape(AbstractBlock:782)
	at net.minecraft.block.Block.isTranslucent(Block:295)
	at net.minecraft.block.AbstractBlock$AbstractBlockState$ShapeCache.<init>(AbstractBlock:1010)
	at net.minecraft.block.AbstractBlock$AbstractBlockState$ShapeCache.<init>(AbstractBlock:994)
	at net.minecraft.block.AbstractBlock$AbstractBlockState.initShapeCache(AbstractBlock:643)
	at net.minecraft.class_2246$$Lambda$10099/1331156786.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at net.minecraft.block.Blocks.refreshShapeCache(Blocks:892)
	at net.minecraft.tag.TagManager.apply(TagManager:24)
	at net.minecraft.resource.ServerResourceManager.loadRegistryTags(ServerResourceManager:88)
	at net.minecraft.client.MinecraftClient.startIntegratedServer(MinecraftClient:1842)
	at net.minecraft.client.MinecraftClient.method_29609(MinecraftClient:1826)
	at net.minecraft.class_310$$Lambda$10066/1143761119.run(Unknown Source)
	at net.minecraft.client.MinecraftClient.method_29605(MinecraftClient:1927)
	at net.minecraft.class_310$$Lambda$10067/215126238.accept(Unknown Source)
	at net.minecraft.client.gui.screen.ConfirmScreen.method_19799(ConfirmScreen:41)
	at net.minecraft.class_410$$Lambda$8612/1313037434.onPress(Unknown Source)
	at net.minecraft.client.gui.widget.ButtonWidget.onPress(ButtonWidget:33)
	at net.minecraft.client.gui.widget.PressableWidget.onClick(PressableWidget:16)
	at net.minecraft.client.gui.widget.ClickableWidget.mouseClicked(ClickableWidget:149)
	at net.minecraft.client.gui.ParentElement.mouseClicked(ParentElement:27)
	at net.minecraft.client.Mouse.method_1611(Mouse:92)
	at net.minecraft.class_312$$Lambda$8519/630583475.run(Unknown Source)
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen:435)
	at net.minecraft.client.Mouse.onMouseButton(Mouse:92)
	at net.minecraft.client.Mouse.method_22686(Mouse:162)
	at net.minecraft.class_312$$Lambda$8518/2071920442.run(Unknown Source)
	at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor:94)
	at net.minecraft.client.Mouse.method_22684(Mouse:162)
	at net.minecraft.class_312$$Lambda$7697/767592530.invoke(Unknown Source)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem:109)
	at net.minecraft.client.util.Window.swapBuffers(Window:308)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1068)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:681)
	at net.minecraft.client.main.Main.main(Main:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.github.chainmailstudios.astromine.transportations.common.block.CatwalkBlock.method_9530(CatwalkBlock.java:140)
	at net.minecraft.class_4970$class_4971.method_26172(class_4970.java:786)
	at net.minecraft.class_4970$class_4971.method_26218(class_4970.java:782)
	at net.minecraft.class_2248.method_9579(class_2248.java:295)
	at net.minecraft.class_4970$class_4971$class_3752.<init>(class_4970.java:1010)
	at net.minecraft.class_4970$class_4971$class_3752.<init>(class_4970.java:994)
	at net.minecraft.class_4970$class_4971.method_26200(class_4970.java:643)
	at net.minecraft.class_2246$$Lambda$10099/1331156786.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at net.minecraft.class_2246.method_26979(class_2246.java:892)
	at net.minecraft.class_5415.method_30222(class_5415.java:24)
	at net.minecraft.class_5350.method_29475(class_5350.java:88)

-- Starting integrated server --
Details:
	Level ID: New World
	Level Name: New World
Stacktrace:
	at Not Enough Crashes deobfuscated stack trace.(1.16.5+build.10)
	at java.lang.Thread.getStackTrace(Thread.java:1552)
	at net.minecraft.util.crash.CrashReportSection.trimStackTraceEnd(CrashReportSection:521)
	at net.minecraft.util.crash.CrashReport.addElement(CrashReport:226)
	at net.minecraft.util.crash.CrashReport.addElement(CrashReport:197)
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen:438)
	at net.minecraft.client.Mouse.onMouseButton(Mouse:92)
	at net.minecraft.client.Mouse.method_22686(Mouse:162)
	at net.minecraft.class_312$$Lambda$8518/2071920442.run(Unknown Source)
	at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor:94)
	at net.minecraft.client.Mouse.method_22684(Mouse:162)
	at net.minecraft.class_312$$Lambda$7697/767592530.invoke(Unknown Source)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem:109)
	at net.minecraft.client.util.Window.swapBuffers(Window:308)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1068)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:681)
	at net.minecraft.client.main.Main.main(Main:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected screen --
Details:
	Screen name: net.minecraft.class_410
Stacktrace:
	at net.minecraft.class_437.method_25412(class_437.java:435)
	at net.minecraft.class_312.method_1601(class_312.java:92)
	at net.minecraft.class_312.method_22686(class_312.java:162)
	at net.minecraft.class_312$$Lambda$8518/2071920442.run(Unknown Source)
	at net.minecraft.class_1255.execute(class_1255.java:94)
	at net.minecraft.class_312.method_22684(class_312.java:162)
	at net.minecraft.class_312$$Lambda$7697/767592530.invoke(Unknown Source)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:109)
	at net.minecraft.class_1041.method_15998(class_1041.java:308)
	at net.minecraft.class_310.method_1523(class_310.java:1068)
	at net.minecraft.class_310.method_1514(class_310.java:681)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by vini2003** [comment]
Closed, since catwalks have been removed.
