### ISSUE TITLE
Critical injection failure: @Inject annotation on renderClouds could not find any targets

### ISSUE THREAD

**Issue by pmcrwf-mid** [Chainmail-Studios/Astromine#431]
I've build the mod from 1.20.1 dev branch and got this error
```
[Render thread/ERROR]: Mixin apply for mod astromine failed astromine.mixins.json:client.WorldRendererMixin from mod astromine -> net.minecraft.class_761: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Critical injection failure: @Inject annotation on renderClouds could not find any targets matching 'Lnet/minecraft/class_761;renderClouds(Lnet/minecraft/class_4587;Lnet/minecraft/util/math/Matrix4f;FDDD)V' in net.minecraft.class_761. Using refmap Astromine-refmap.json [PREINJECT Applicator Phase -> astromine.mixins.json:client.WorldRendererMixin from mod astromine -> Prepare Injections ->  -> handler$zin000$astromine$renderClouds(Lnet/minecraft/class_4587;Lorg/joml/Matrix4f;FDDDLorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on renderClouds could not find any targets matching 'Lnet/minecraft/class_761;renderClouds(Lnet/minecraft/class_4587;Lnet/minecraft/util/math/Matrix4f;FDDD)V' in net.minecraft.class_761. Using refmap Astromine-refmap.json [PREINJECT Applicator Phase -> astromine.mixins.json:client.WorldRendererMixin from mod astromine -> Prepare Injections ->  -> handler$zin000$astromine$renderClouds(Lnet/minecraft/class_4587;Lorg/joml/Matrix4f;FDDDLorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.validateTargets(InjectionInfo.java:656) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findTargets(InjectionInfo.java:587) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:330) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:316) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:308) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:46) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:483) ~[?:?]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:149) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:708) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1329) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1053) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.14.24.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	at java.lang.Class.getDeclaredFields0(Native Method) ~[?:?]
	at java.lang.Class.privateGetDeclaredFields(Class.java:3329) ~[?:?]
	at java.lang.Class.getDeclaredFields(Class.java:2403) ~[?:?]
	at dev.latvian.mods.rhino.JavaMembers.getDeclaredFieldsSafe(JavaMembers.java:843) ~[rhino-fabric-2001.2.2-build.13.jar:?]
	at dev.latvian.mods.rhino.JavaMembers.getAccessibleFields(JavaMembers.java:686) ~[rhino-fabric-2001.2.2-build.13.jar:?]
	at dev.latvian.mods.rhino.JavaMembers.reflect(JavaMembers.java:512) ~[rhino-fabric-2001.2.2-build.13.jar:?]
	at dev.latvian.mods.rhino.JavaMembers.<init>(JavaMembers.java:261) ~[rhino-fabric-2001.2.2-build.13.jar:?]
	at dev.latvian.mods.rhino.JavaMembers.lookupClass(JavaMembers.java:208) ~[rhino-fabric-2001.2.2-build.13.jar:?]
	at dev.latvian.mods.rhino.NativeJavaObject.initMembers(NativeJavaObject.java:602) ~[rhino-fabric-2001.2.2-build.13.jar:?]
	at dev.latvian.mods.rhino.NativeJavaObject.<init>(NativeJavaObject.java:592) ~[rhino-fabric-2001.2.2-build.13.jar:?]
	at dev.latvian.mods.rhino.NativeJavaObject.<init>(NativeJavaObject.java:584) ~[rhino-fabric-2001.2.2-build.13.jar:?]
	at dev.latvian.mods.rhino.WrapFactory.wrapAsJavaObject(WrapFactory.java:140) ~[rhino-fabric-2001.2.2-build.13.jar:?]
	at dev.latvian.mods.rhino.WrapFactory.wrap(WrapFactory.java:78) ~[rhino-fabric-2001.2.2-build.13.jar:?]
	at dev.latvian.mods.rhino.Context.javaToJS(Context.java:250) ~[rhino-fabric-2001.2.2-build.13.jar:?]
	at dev.latvian.mods.rhino.Context.addToScope(Context.java:1185) ~[rhino-fabric-2001.2.2-build.13.jar:?]
	at dev.latvian.mods.kubejs.script.BindingsEvent.add(BindingsEvent.java:20) ~[kubejs-fabric-2001.6.3-build.83.jar:?]
	at dev.latvian.mods.kubejs.client.BuiltinKubeJSClientPlugin.registerBindings(BuiltinKubeJSClientPlugin.java:22) ~[kubejs-fabric-2001.6.3-build.83.jar:?]
	at dev.latvian.mods.kubejs.script.ScriptManager.load(ScriptManager.java:188) ~[kubejs-fabric-2001.6.3-build.83.jar:?]
	at dev.latvian.mods.kubejs.script.ScriptManager.reload(ScriptManager.java:80) ~[kubejs-fabric-2001.6.3-build.83.jar:?]
	at dev.latvian.mods.kubejs.client.KubeJSClient.reloadClientScripts(KubeJSClient.java:67) ~[kubejs-fabric-2001.6.3-build.83.jar:?]
	at dev.latvian.mods.kubejs.client.KubeJSClient.init(KubeJSClient.java:51) ~[kubejs-fabric-2001.6.3-build.83.jar:?]
	at dev.latvian.mods.kubejs.KubeJS.<init>(KubeJS.java:149) ~[kubejs-fabric-2001.6.3-build.83.jar:?]
	at dev.latvian.mods.kubejs.fabric.KubeJSFabric.onInitialize(KubeJSFabric.java:34) ~[kubejs-fabric-2001.6.3-build.83.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:383) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52) ~[fabric-loader-0.14.24.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:458) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:211) ~[minecraft-1.20.1-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.24.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) ~[NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) ~[NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) ~[NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) ~[NewLaunch.jar:?]
```
Modlist:
```
Astromine-2.0.81.20.1.jar
Block Swap-fabric-1.20.1-5.0.0.0.jar
BodiesBodies-1.0.1.jar
Bookshelf-Fabric-1.20.1-20.1.7.jar
Continents_1.20.2_v1.1.3.jar
Controlify-1.6.0+1.20.jar
Display Case-fabric-1.20-1.0.7.jar
ElytraAeronautics-1.3.0.jar
Flotage-Fabric-1.20.1-1.2.1.jar
ForgeConfigAPIPort-v8.0.0-1.20.1-Fabric.jar
FriendlyFire-Fabric-1.20.1-18.0.5.jar
ImmediatelyFast-1.2.6+1.20.2.jar
Jade-1.20-fabric-11.6.2.jar
Kiwi-1.20.1-fabric-11.1.1.jar
Ksyxis-1.1.jar
MouseTweaks-fabric-mc1.20-2.25.jar
Neat-1.20-35-FABRIC.jar
NoChatReports-FABRIC-1.20.1-v2.2.2.jar
Patchouli-1.20.1-83-FABRIC.jar
Philips-Ruins1.20.1-2.8[Fabric].jar
Plethora-Fabric-1.9.1.jar
PresenceFootsteps-1.9.1.jar
RoughlyEnoughItems-12.0.672.jar
Rrls-3.2.0-1.20.1-fabric.jar
SnowRealMagic-1.20.1-fabric-9.0.3.jar
TerraBlender-fabric-1.20.1-3.0.0.169.jar
Truly-Modular-Archery-1.2-1.20.1-fabric.jar
Truly-Modular-Armory-1.3-1.20.1-fabric.jar
Truly-Modular-Arsenal-1.3-1.20.1-fabric.jar
Truly-Modular-miapi-fabric-1.1.2-1.20.1.jar
WWOO-FABRIC+FORGE+QUILT-2.0.0.jar
XaeroPlus-Fabric-1.20.1-69-WM1.37.2-MM23.9.3.jar
XaerosWorldMap_1.37.2_Fabric_1.20.jar
Xaeros_Minimap_23.9.3_Fabric_1.20.jar
Zoomify-2.11.2.jar
advancementinfo-1.20-fabric0.83.0-1.4.jar
ae2wtlib-15.1.2-fabric.jar
almostunified-fabric-1.20.1-0.7.0.jar
appliedenergistics2-fabric-15.0.14.jar
architectury-9.1.12-fabric.jar
argonauts-fabric-1.20.1-1.0.6.jar
armourersworkshop-fabric-1.20.1-2.0.10.jar
athena-fabric-1.20.1-3.0.0.jar
autoslabs-1.1.3.jar
balm-fabric-1.20.1-7.1.4.jar
better_climbing-fabric-3.jar
bettermounthud-1.2.2.jar
bounced-1.20-3.1.1.jar
bushierflowers-0.0.3-1.20.1.jar
cadmus-fabric-1.20.1-1.0.2.jar
capes-1.5.2+1.20-fabric.jar
cc-tweaked-1.20.1-fabric-1.108.4.jar
chatanimation-1.0.3.jar
chipped-fabric-1.20.1-3.0.1.jar
clean_tooltips-1.0-fabric-1.20.1.jar
cloth-config-11.1.106-fabric.jar
comforts-fabric-6.3.4+1.20.1.jar
completeconfig-2.5.0.jar
consistency_plus-fabric-0.5.2-rc.4+1.20.1.jar
continuity-3.0.0-beta.4+1.20.1.jar
culinaryconstruct-fabric-5.2.1+1.20.1.jar
dawn-5.0.0.jar
dual-swords-1.0.3.jar
dynamic-fps-3.2.1+minecraft-1.20.0.jar
entangled-1.3.16-fabric-mc1.20.jar
entityculling-fabric-1.6.2-mc1.20.1.jar
everycomp-1.20-2.6.15-fabric.jar
fabric-api-0.91.0+1.20.1.jar
fabric-language-kotlin-1.10.10+kotlin.1.9.10.jar
fabric-seasons-2.2.1+1.20.jar
fabric-seasons-extras-1.2-BETA+1.20.jar
fabricskyboxes-0.7.3+mc1.20.1.jar
fabrishot-1.10.0.jar
fadeless-1.0.1.jar
fastquit-3.0.0+1.20+.jar
ferritecore-6.0.0-fabric.jar
forcecloseloadingscreen-2.1.1.jar
glassential-fabric-2.0.0.jar
gtceu-fabric-1.20.1-1.0.16.jar
harvestwithease-1.20.1-7.1.0.0-fabric.jar
heracles-fabric-1.20.1-1.0.5.jar
indium-1.0.27+mc1.20.1.jar
iris-mc1.20.1-1.6.10.jar.disabled
krypton-0.2.3.jar
kubejs-fabric-2001.6.3-build.83.jar
language-reload-1.5.9+1.20.1.jar
laserbridges-1.20.1-1-fabric.jar
lazydfu-0.1.3.jar
linkedstorage-1.5.2-1.20.jar
lithium-fabric-mc1.20.1-0.11.2.jar
lmft-1.0.2+1.20-fabric.jar
main-menu-credits-1.1.2.jar
megacells-fabric-2.2.2-1.20.1.jar
memoryleakfix-fabric-1.17+-1.1.2.jar
merequester-fabric-1.20.1-1.1.4.jar
mixintrace-1.1.1+1.17.jar
modelfix-1.14-fabric.jar
modlist.txt
modmenu-7.2.2.jar
moonlight-1.20-2.8.56-fabric.jar
morechathistory-1.19.1-1.1.1.jar
moreculling-1.20.1-0.19.0.jar
noisium-1.0.2+mc1.20.x.jar
openblockselevator-0.0.3-1.20.1.jar
owo-lib-0.11.1+1.20.jar
pack_it_up-0.3.1+1.20.1.jar
passableleaves-1.5.1.jar
peripheralium-fabric-1.20.1-0.6.14.jar
peripheralworks-fabric-1.20.1-1.4.2.jar
platforms-fabric-1.20.1-1.1.jar
polymer-bundled-0.5.18+1.20.1.jar
potionring-fabric-1.20-1.0.jar
primalstorage-1.3-1.20-fabric.jar
probejs-5.7.0-fabric.jar
promenade-4.1.1.jar
prometheus-fabric-1.20.1-1.2.1.jar
puzzle-1.5.2+1.20.jar
reeses_sodium_options-1.6.5+mc1.20.1-build.95.jar
resourcefulconfig-fabric-1.20.1-2.1.0.jar
resourcefullib-fabric-1.20.1-2.1.16.jar
rhino-fabric-2001.2.2-build.13.jar
rpgz-0.6.0.jar
sc-peripherals-1.7.1.jar
shetiphiancore-fabric-1.20.1-1.2.jar
shulkerboxslot-fabric-5.1.1+1.20.1.jar
sodium-extra-0.5.1+mc1.20.1-build.112.jar
sodium-fabric-mc1.20.1-0.5.3.jar
spark-1.10.53-fabric.jar
speedometer-1.3.1.jar
spoiledz-1.0.8.jar
starlight-1.1.2+fabric.dbc156f.jar
supermartijn642configlib-1.1.8a-fabric-mc1.20.jar
supermartijn642corelib-1.1.16-fabric-mc1.20.1.jar
tempad-fabric-1.20.1-2.1.1.jar
thermite-4.1.0_mc-1.20.1.jar
threadtweak-fabric-1.20.2-0.1.1.jar
toms_storage_fabric-1.20-1.6.5.jar
tree-hollows-fabric-3.1.0.jar
trinkets-3.7.1.jar
turtlematic-fabric-1.20.1-1.2.5.jar
variantbarrels-3.3.6.jar
variantbookshelves-2.3.6.jar
variantchests-1.3.5.jar
variantchiseledbookshelves-1.3.5.jar
variantcraftingtables-6.3.5.jar
voicechat-fabric-1.20.1-2.4.31.jar
walkietalkie-fabric-1.20-1.20.1-1.2.2.jar
waystones-fabric-1.20-14.0.2.jar
whats-that-slot-fabric-1.3.4+1.20.1.jar
wired-redstone-0.7.7+1.20.1.jar
wirelessnetworks-1.7.1.jar
xaeros_waystones_compability-1.19.2-1.20.1--1.0.jar
yet-another-config-lib-fabric-3.2.1+1.20.jar
yosbr-0.1.2.jar
```

**Comment by vini2003** [comment]
The mod is mostly abandoned since we moved on due to work and university. Sadly we can't really fix this right now.

**Comment by vini2003** [comment]
This issue has now been addressed in the NeoForge 1.21.1 port. Older versions are no longer supported.
